import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile, stat } from 'node:fs/promises';
import { createServer } from 'node:http';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PAGE_PATH = path.join(ROOT, 'tools', 'forfettario', 'index.html');
const MIME = new Map([['.css','text/css; charset=utf-8'],['.html','text/html; charset=utf-8'],['.ico','image/x-icon'],['.js','text/javascript; charset=utf-8'],['.json','application/json; charset=utf-8'],['.png','image/png'],['.svg','image/svg+xml'],['.woff2','font/woff2']]);
const FATTURAPA_HASH = 'E14C3EFEC2A434DFF7505523CD494E0FC55318E8B3F61146643375643FC2D62D';
const SENTINELS = ['SENTINEL_NAME_10B','SENTINEL_CF_10B','SENTINEL_VAT_10B','SENTINEL_CLIENT_10B','SENTINEL_INVOICE_10B','SENTINEL_CUSTOMER_10B','SENTINEL_XML_10B','SENTINEL_NOTE_10B','SENTINEL_FILE_10B','SENTINEL_HASH_10B'];
const boolDomain={type:'boolean',allowedValues:[true,false]},enumDomain=allowedValues=>({type:'enum',allowedValues}),intDomain=(min,max,step=1)=>({type:'integer',min,max,step});
const PENSION_FACT_CONTRACT={
  inpsGs:[{id:'otherMandatoryCoverage',domain:boolDomain}],
  inpsCraftTrade:[{id:'ageRateProfile',domain:enumDomain(['adult','under21']),calculationDomain:{allowedValues:['adult'],message:'Profilo valido non calcolabile.'}},{id:'contributionHistory',domain:enumDomain(['pre1996','post1995'])},{id:'reductionMode',domain:enumDomain(['none','forfettario35','new2025_50']),calculationConditions:[{whenValues:['new2025_50'],contextFact:'activityStartYear',allowedValues:[2025],code:'PENSION_NEW_2025_ACTIVITY_START_REQUIRED',field:'taxFacts.activityStartYear',message:'Avvio 2025 richiesto.'}]},{id:'reductionEligibilityConfirmed',domain:boolDomain,requiredWhen:{factId:'reductionMode',values:['forfettario35','new2025_50']},calculationDomain:{allowedValues:[true],message:'Conferma richiesta.'}}],
  cnpadc:[{id:'subjectiveRateBps',domain:intDomain(1200,10000)},{id:'minimumProfile',domain:enumDomain(['ordinary','no_minima'])}],cnpr:[{id:'subjectiveRateBps',domain:intDomain(1500,2500)},{id:'subjectiveMinimumMode',domain:enumDomain(['full','half','none'])},{id:'supplementaryMinimumMode',domain:enumDomain(['full','half','none'])},{id:'integrativeMinimumApplies',domain:boolDomain}],
  geometri:[{id:'minimumProfile',domain:enumDomain(['ordinary','no_minima']),calculationDomain:{allowedValues:['ordinary'],message:'Profilo valido non calcolabile.'}}],enasarco:[{id:'mandateType',domain:enumDomain(['mono','pluri'])}],enpacl:[{id:'rateProfile',domain:enumDomain(['ordinary','reduced'])},{id:'reductionEligibilityConfirmed',domain:boolDomain,requiredWhen:{factId:'rateProfile',values:['reduced']},calculationDomain:{allowedValues:[true],message:'Conferma richiesta.'}}],
  enpap:[{id:'subjectiveRateBps',domain:intDomain(1000,3000,200)},{id:'subjectiveMinimumCents',domain:{type:'integer',allowedValuesFrom:'allowedMinimumsCents',allowedValues:[85600,42800,28600,17200]}}],epap:[{id:'subjectiveRateBps',domain:intDomain(1000,10000)},{id:'minimumProfile',domain:enumDomain(['ordinary','no_minima']),calculationDomain:{allowedValues:['ordinary'],message:'Profilo valido non calcolabile.'}}],inpgiGs:[{id:'minimumProfile',domain:enumDomain(['ordinary','no_minima']),calculationDomain:{allowedValues:['ordinary'],message:'Profilo valido non calcolabile.'}}]
};
const PENSION_MATRIX=[
  ['INPS_GS','INPS Gestione Separata','CALCOLABILE','CALCOLABILE','inpsGs','inpsGs'],['INPS_ARTIGIANI','INPS Artigiani','CALCOLABILE','CALCOLABILE','inpsCraftTrade','inpsCraftTrade'],['INPS_COMMERCIANTI','INPS Commercianti','CALCOLABILE','CALCOLABILE','inpsCraftTrade','inpsCraftTrade'],
  ['ENASARCO','ENASARCO','PARZIALE','CALCOLABILE',null,'enasarco'],['CASSA_FORENSE','Cassa Forense','PARZIALE','PARZIALE'],['CNPADC','CNPADC','CALCOLABILE','PARZIALE','cnpadc'],['CNPR','CNPR','CALCOLABILE','PARZIALE','cnpr'],['INARCASSA','Inarcassa','PARZIALE','PARZIALE'],
  ['CASSA_GEOMETRI','Cassa Geometri','PARZIALE','CALCOLABILE',null,'geometri'],['ENPACL','ENPACL','PARZIALE','CALCOLABILE',null,'enpacl'],['ENPAM','ENPAM','PARZIALE','PARZIALE'],['ENPAP','ENPAP','CALCOLABILE','PARZIALE','enpap'],['ENPAV','ENPAV','PARZIALE','BLOCCATO'],
  ['EPPI','EPPI','BLOCCATO','BLOCCATO'],['EPAP','EPAP','CALCOLABILE','PARZIALE','epap'],['ENPAF','ENPAF','BLOCCATO','BLOCCATO'],['ENPAB','ENPAB','PARZIALE','PARZIALE'],['INPGI_GS','INPGI Gestione Separata','CALCOLABILE','CALCOLABILE','inpgiGs','inpgiGs'],
  ['ENPAIA_PERITI','ENPAIA Periti Agrari','PARZIALE','BLOCCATO'],['ENPAIA_AGROTECNICI','ENPAIA Agrotecnici','BLOCCATO','BLOCCATO'],['ENPAPI','ENPAPI','PARZIALE','PARZIALE'],['NOTARIATO','Cassa Nazionale del Notariato','PARZIALE','PARZIALE']
];

const sha256 = value => createHash('sha256').update(value,'utf8').digest('hex').toUpperCase();
function scriptBody(source,id){const match=source.match(new RegExp(`<script id="${id}">\\r?\\n?([\\s\\S]*?)<\\/script>`));assert.ok(match,`blocco ${id} presente`);return match[1];}
const sum = values => values.reduce((total,value)=>total+value,0);
function configEnvelope(){
  return {status:'calculated',result:{schemas:{calculation:'forfettario-calculation-v1',atecoResolution:'forfettario-ateco-resolution-v1'},supportedYears:[2025,2026],pensionFactContractVersion:'forfettario-pension-facts-v2',pensionManagements:PENSION_MATRIX.map(([id,label,status2025,status2026,adapter2025,adapter2026])=>({id,label,years:[[2025,status2025,adapter2025],[2026,status2026,adapter2026]].map(([year,status,adapter])=>({year,status,requiredFacts:status==='CALCOLABILE'?(PENSION_FACT_CONTRACT[adapter]||[]):[],source:'fixture contrattuale',rulePackId:`${id.toLowerCase()}-${year}-v1`}))})),rulePacks:[2025,2026].map(year=>({year,id:`it-forfettario-${year}-v1`})),atecoCatalogRelease:'ISTAT-ATECO-2025-2026-07-15',atecoCrosswalkRelease:'fixture-crosswalk'},diagnostics:[],engineVersion:'forfettario-test-worker-v1',rulePackId:null,pensionRulePackId:null,atecoCrosswalkRelease:'fixture-crosswalk'};
}
function outcome(year,value,diagnostics=[]){return {status:diagnostics.length?'blocked':'calculated',value:diagnostics.length?null:value,diagnostics,rulePackId:`it-forfettario-${year}-v1`,appliedRules:[]};}
function pensionDomainAccepts(domain,value){if(!domain)return true;if(domain.type==='boolean')return typeof value==='boolean';if(domain.type==='enum')return typeof value==='string'&&domain.allowedValues.includes(value);if(domain.type==='integer'){if(!Number.isSafeInteger(value))return false;if(Array.isArray(domain.allowedValues))return domain.allowedValues.includes(value);return (domain.min===undefined||value>=domain.min)&&(domain.max===undefined||value<=domain.max)&&(value-(domain.min||0))%(domain.step||1)===0;}if(Array.isArray(domain.allowedValues))return domain.allowedValues.includes(value);return true;}
function pensionFixtureOutcome(payload,totalCents){const row=PENSION_MATRIX.find(item=>item[0]===payload.pensionFacts.managementId),yearIndex=payload.year===2025?2:3,adapterIndex=payload.year===2025?4:5,status=row&&row[yearIndex],adapter=row&&row[adapterIndex],options=payload.pensionFacts.options||{};if(status!=='CALCOLABILE')return outcome(payload.year,null,[{code:status==='PARZIALE'?'PENSION_ADAPTER_PARTIAL':'PENSION_ADAPTER_BLOCKED',field:'pensionFacts.managementId',message:'La gestione richiede una verifica esterna.'}]);const declared=PENSION_FACT_CONTRACT[adapter]||[];for(const specification of declared){const value=options[specification.id];if(value!==undefined&&value!==null&&value!==''&&!pensionDomainAccepts(specification.domain,value))return outcome(payload.year,null,[{code:'PENSION_FACT_INVALID',field:`pensionFacts.options.${specification.id}`,message:'Valore non valido.'}]);}const specs=declared.filter(item=>!item.requiredWhen||item.requiredWhen.values.includes(options[item.requiredWhen.factId]));for(const specification of specs){const value=options[specification.id];if(value===undefined||value===null||value==='')return outcome(payload.year,null,[{code:'PENSION_FACTS_MISSING',field:`pensionFacts.options.${specification.id}`,message:'Completa i dati previdenziali.'}]);if(!pensionDomainAccepts(specification.calculationDomain||specification.domain,value))return outcome(payload.year,null,[{code:'PENSION_CONFIGURATION_NOT_CALCULABLE',field:`pensionFacts.options.${specification.id}`,message:(specification.calculationDomain||{}).message||'Configurazione non calcolabile.'}]);for(const condition of specification.calculationConditions||[]){if(condition.whenValues.includes(value)&&!condition.allowedValues.includes(payload.taxFacts[condition.contextFact]))return outcome(payload.year,null,[{code:condition.code,field:condition.field,message:condition.message}]);}}return outcome(payload.year,{totalCents,components:{subjectiveCents:totalCents}});}
function calculationEnvelope(payload){
  const coefficient=code=>code.startsWith('62.')?6700:7800;
  const byActivity=payload.activities.map(item=>({activityId:item.key,cashCents:item.fiscalCashCents,coefficientBps:coefficient(item.atecoCode),grossIncomeCents:Math.round(item.fiscalCashCents*coefficient(item.atecoCode)/10000)}));
  const grossIncomeCents=sum(byActivity.map(item=>item.grossIncomeCents)),taxableIncomeCents=Math.max(0,grossIncomeCents-payload.taxFacts.deductibleContributionsPaidCents),taxCents=Math.round(taxableIncomeCents*(payload.taxFacts.startupRateRequested?5:15)/100),socialCents=Math.round(grossIncomeCents/10);
  const actualCashCents=Math.max(0,sum(payload.activities.map(item=>item.thresholdCashCents))),expectedCashCents=sum([payload.forecast.expectedReceiptsCents,payload.forecast.newCompensationCents].filter(Number.isInteger)),forecastMissing=expectedCashCents>0&&!payload.forecast.activityKey;
  const eligibility=outcome(payload.year,{eligible:true,immediateExit:false,nextYearExit:false}),income=outcome(payload.year,{grossIncomeCents,deductibleContributionsCents:payload.taxFacts.deductibleContributionsPaidCents,taxableIncomeCents,byActivity}),social=pensionFixtureOutcome(payload,socialCents),tax=outcome(payload.year,{rateBps:payload.taxFacts.startupRateRequested?500:1500,taxCents});
  const advanceMissing=payload.taxFacts.priorYearTaxCents===null||payload.taxFacts.validAdvancesPaidCents===null,advanceTotal=payload.taxFacts.priorYearTaxCents||0,advanceRows=advanceTotal<=5165?[]:advanceTotal<25752?[{number:2,amountCents:advanceTotal,taxCode:'1791'}]:[{number:1,amountCents:Math.round(advanceTotal*.4),taxCode:'1790'},{number:2,amountCents:advanceTotal-Math.round(advanceTotal*.4),taxCode:'1791'}],advances=advanceMissing?outcome(payload.year,null,[{code:'ADVANCE_INPUTS_MISSING',message:'Completa saldo e acconti.'}]):outcome(payload.year,{balance:{debitCents:Math.max(0,taxCents-payload.taxFacts.validAdvancesPaidCents)},installments:advanceRows}),calendarEvents=advanceRows.map(item=>({date:item.number===2?`${payload.year}-11-30`:`${payload.year}-06-30`,entity:'ERARIO',code:item.taxCode,kind:item.number===2?'advance_second_or_single':'balance_or_first_advance',amountCents:item.amountCents,referenceYear:payload.year,status:'planned'}));
  if(payload.year===2026)calendarEvents.push({date:'2027-11-30',entity:'ERARIO',code:'1791',kind:'advance_second_or_single',amountCents:12345,referenceYear:2027,status:'planned'});
  const calendar=advanceMissing?outcome(payload.year,null,[{code:'CALENDAR_INPUTS_MISSING',message:'Completa saldo e acconti.'}]):outcome(payload.year,{events:calendarEvents});
  const forecast=forecastMissing?outcome(payload.year,null,[{code:'FORECAST_ACTIVITY_REQUIRED',message:'Scegli l’attività.'}]):outcome(payload.year,{actualCashCents,expectedCashCents,projectedCashCents:actualCashCents+expectedCashCents,expectedEvents:[]}),reserveCents=Math.max(0,taxCents+socialCents-payload.taxFacts.deductibleContributionsPaidCents-(payload.taxFacts.validAdvancesPaidCents||0)),projected=forecastMissing?{status:'blocked',diagnostics:forecast.diagnostics}:{status:'calculated',taxCents,socialCents,reserveCents,tax,social,diagnostics:[]};
  const result={eligibility,income,social,tax,advances,calendar,forecast,projected,paidContributionCents:payload.taxFacts.deductibleContributionsPaidCents,reserveCents,ateco:payload.activities.map(item=>({key:item.key,atecoCode:item.atecoCode,status:'calculated',value:{coefficientBps:coefficient(item.atecoCode),groupId:'FIXTURE'},diagnostics:[]}))};
  return {status:[social,advances,calendar,forecast].some(item=>item.status==='blocked')?'blocked':'calculated',result,diagnostics:[],engineVersion:'forfettario-test-worker-v1',rulePackId:`it-forfettario-${payload.year}-v1`,pensionRulePackId:`${payload.pensionFacts.managementId.toLowerCase()}-${payload.year}-v1`,atecoCrosswalkRelease:'fixture-crosswalk',calculationId:`fixture-${payload.year}`};
}
async function startServer(){
  const requests=[],apiRequests=[],missing=[];let failNext=false;
  const server=createServer(async(request,response)=>{
    try{
      const url=new URL(request.url,'http://127.0.0.1');
      if(url.pathname==='/__forfettario-race'){response.writeHead(200,{'content-type':'text/html; charset=utf-8'});response.end('<!doctype html><title>race</title>');return;}
      if(url.pathname.startsWith('/api/')){
        let body='';for await(const chunk of request)body+=chunk;apiRequests.push({method:request.method,url:request.url,headers:request.headers,body});
        const json=value=>{response.writeHead(200,{'content-type':'application/json; charset=utf-8'});response.end(JSON.stringify(value));};
        if(url.pathname==='/api/stato')return json({ok:true});
        if(url.pathname==='/api/forfettario/config')return json(configEnvelope());
        if(url.pathname==='/api/forfettario/ateco/risolvi'){const payload=JSON.parse(body);return json({status:'calculated',result:{coefficientBps:payload.atecoCode.startsWith('62.')?6700:7800,groupId:'FIXTURE'},diagnostics:[],engineVersion:'forfettario-test-worker-v1',rulePackId:`it-forfettario-${payload.year}-v1`,pensionRulePackId:null,atecoCrosswalkRelease:'fixture-crosswalk'});}
        if(url.pathname==='/api/forfettario/calcola'){if(failNext){failNext=false;response.writeHead(503,{'content-type':'application/json'});return response.end('{}');}return json(calculationEnvelope(JSON.parse(body)));}
        response.writeHead(404).end('Not found');return;
      }
      let relative=decodeURIComponent(url.pathname).replace(/^\/+/,'');if(!relative||relative.endsWith('/'))relative+='index.html';const absolute=path.resolve(ROOT,relative);requests.push(relative);if(absolute!==ROOT&&!absolute.startsWith(`${ROOT}${path.sep}`)){response.writeHead(403).end('Forbidden');return;}await stat(absolute);response.writeHead(200,{'content-type':MIME.get(path.extname(absolute))||'application/octet-stream'});response.end(await readFile(absolute));
    }catch{missing.push(request.url);response.writeHead(404).end('Not found');}
  });
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
  return {baseUrl:`http://127.0.0.1:${server.address().port}`,requests,apiRequests,missing,failNext:()=>{failNext=true;},close:()=>new Promise(resolve=>server.close(resolve))};
}

test('Forfettario 10B: route contiene solo documenti locali e client authoritative',async()=>{
  const source=await readFile(PAGE_PATH,'utf8'),engine=scriptBody(source,'forfettario-engine-v6'),fatturaPa=scriptBody(source,'forfettario-fatturapa-import'),ui=scriptBody(source,'forfettario-tal-ui-v8');
  assert.match(source,/<meta name="robots" content="noindex,nofollow">/);assert.match(source,/\/assets\/tal-api-connection\.js/);assert.match(source,/\.\/authoritative-client\.js/);assert.match(source,/forfettario-calculation-v1/);assert.equal(sha256(fatturaPa),FATTURAPA_HASH);
  for(const forbidden of ['PENSION_PARAMETERS','PENSION_REGISTRY','ANNEX4_RULE_SETS','AtecoCrosswalkRelease','resolveAtecoCoefficient','calculateForfaitIncome','calculateSocialSecurity','calculateTax','calculateAdvancesAndBalance','calculateForecast','buildPaymentCalendar'])assert.doesNotMatch(source,new RegExp(forbidden));
  assert.match(engine,/ATECO_CATALOG_PACKED/);assert.doesNotMatch(source,/workers\.dev|localStorage[^\n]{0,120}(?:endpoint|apiUrl)|100% locale · nessun dato lascia/i);assert.doesNotMatch(source,/localStorage\.clear\s*\(/);assert.doesNotMatch(ui,/\b(?:alert|confirm|prompt)\s*\(|\.toFixed\s*\(/);assert.match(ui,/Intl\.NumberFormat\('it-IT'.*useGrouping:true/);assert.match(source,/id="confirmationModal"[^>]*role="dialog"[^>]*aria-modal="true"/);
});

test('Forfettario 10B: regressioni distribuite, privacy payload, race e reload',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1440,height:1000}}),page=await context.newPage(),consoleErrors=[],pageErrors=[],external=[];
  page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});page.on('pageerror',error=>pageErrors.push(error.message));page.on('request',request=>{if(new URL(request.url()).origin!==server.baseUrl)external.push(request.url());});page.on('dialog',dialog=>{pageErrors.push(`Native dialog inatteso: ${dialog.type()}`);dialog.dismiss();});
  await page.goto(`${server.baseUrl}/tools/forfettario/?forfettario-engine-tests=1&forfettario-fatturapa-tests=1`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.__FORFETTARIO_ENGINE_TEST_RESULT__&&globalThis.__FORFETTARIO_FATTURA_PA_TEST_RESULT__||globalThis.__FORFETTARIO_FATTURAPA_TEST_RESULT__);
  await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());await page.evaluate(()=>globalThis.ForfettarioPersonalApp.loadDemo());await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.diagnostics().hasResult);
  const reports=await page.evaluate(async()=>({Below:globalThis.__FORFETTARIO_ENGINE_TEST_RESULT__,fatturaPa:globalThis.__FORFETTARIO_FATTURAPA_TEST_RESULT__,personal:globalThis.ForfettarioPersonalApp.runBrowserRegressions(),professional:await globalThis.ForfettarioProfessionalApp.runBrowserRegressions()}));reports.engine=reports.Below;delete reports.Below;
  assert.equal(reports.personal.failed,0,JSON.stringify(reports.personal.failures));assert.equal(reports.professional.failed,0,JSON.stringify(reports.professional.failures));assert.deepEqual(Object.fromEntries(Object.entries(reports).map(([name,report])=>[name,`${report.passed}/${report.total}`])),{fatturaPa:'80/80',personal:'128/128',professional:'41/41',engine:'70/70'});assert.equal(Object.values(reports).reduce((n,r)=>n+r.failed,0),0);
  const privacy=await page.evaluate(async sentinels=>{const app=globalThis.ForfettarioPersonalApp,draft=app.loadDemo();Object.assign(draft,{clientId:sentinels[3],practiceId:sentinels[3]+'-P',professionalNote:sentinels[7]});draft.profile.name=sentinels[0];draft.profile.taxCode=sentinels[1];draft.profile.vatCode=sentinels[2];Object.assign(draft.ledger.invoices[0],{number:sentinels[4],customer:sentinels[5],xml:sentinels[6]});draft.ledger.invoices[0].origin={type:'FatturaPA',fileName:sentinels[8],contentHash:sentinels[9]};const built=app.buildCalculationPayload(draft);await globalThis.ForfettarioAuthoritative.schedule(built.payload);return {built,diagnostics:globalThis.ForfettarioAuthoritative.diagnostics()};},SENTINELS);
  assert.equal(privacy.built.status,'calculated');assert.equal(privacy.diagnostics.hasResult,true);
  const pensionPrivacy=await page.evaluate(sentinel=>{const app=globalThis.ForfettarioPersonalApp,draft=app.loadDemo();draft.profile.pension.options.professionalNote=sentinel;draft.profile.pension.options.freeText=sentinel;return JSON.stringify(app.buildCalculationPayload(draft));},SENTINELS[7]);assert.equal(pensionPrivacy.includes(SENTINELS[7]),false,'i fatti previdenziali non consentono testo libero');
  const transport=server.apiRequests.map(item=>`${item.url}\n${JSON.stringify(item.headers)}\n${item.body}`).join('\n');for(const sentinel of SENTINELS)assert.equal(transport.includes(sentinel),false,`sentinella esclusa: ${sentinel}`);
  const posts=server.apiRequests.filter(item=>item.url==='/api/forfettario/calcola'),body=posts.map(item=>item.body).join('\n');assert.doesNotMatch(body,/personalState|invoices|payments|allocations|customer|taxCode|vatCode|fileName|contentHash|xml/i);
  const payload=JSON.parse(posts.at(-1).body);assert.deepEqual(Object.keys(payload).sort(),['activities','eligibilityFacts','forecast','pensionFacts','schema','taxFacts','year']);assert.ok(payload.activities.every(item=>/^A\d+$/.test(item.key)));
  const clientSource=await readFile(path.join(ROOT,'tools','forfettario','authoritative-client.js'),'utf8'),racePage=await context.newPage();await racePage.goto(`${server.baseUrl}/__forfettario-race`);await racePage.evaluate(()=>{globalThis.TAL_API={invalidate(){},async request(_path,options){const payload=JSON.parse(options.body),slow=payload.marker==='old';await new Promise((resolve,reject)=>{const timer=setTimeout(resolve,slow?80:5);options.signal?.addEventListener('abort',()=>{clearTimeout(timer);reject(new DOMException('aborted','AbortError'));},{once:true});});return new Response(JSON.stringify({status:'calculated',result:{marker:payload.marker},diagnostics:[],engineVersion:'race-v1',rulePackId:'race-pack'}),{status:200,headers:{'content-type':'application/json'}});}};});await racePage.addScriptTag({content:clientSource});const race=await racePage.evaluate(async()=>{const first={marker:'old'},second={marker:'new'},one=globalThis.ForfettarioAuthoritative.schedule(first),two=globalThis.ForfettarioAuthoritative.schedule(second);await Promise.allSettled([one,two]);const result={first:globalThis.ForfettarioAuthoritative.snapshot(first).status,second:globalThis.ForfettarioAuthoritative.snapshot(second)};globalThis.TAL_API.request=async()=>new Response('{}',{status:503,headers:{'content-type':'application/json'}});const failed={marker:'failed'};await globalThis.ForfettarioAuthoritative.schedule(failed);result.failed=globalThis.ForfettarioAuthoritative.snapshot(failed);return result;});await racePage.close();assert.equal(race.first,'stale');assert.equal(race.second.status,'calculated',JSON.stringify(race));assert.equal(race.second.result.marker,'new');assert.equal(race.failed.status,'error');assert.equal(race.failed.result,null);assert.equal(race.failed.diagnostics[0].message,'Il servizio di calcolo non è temporaneamente disponibile. I tuoi dati locali non sono stati persi.');
  const persistence=await page.evaluate(()=>{const app=globalThis.ForfettarioPersonalApp,draft=app.loadDemo();draft.demo=false;draft.mode='personal';draft.onboarding.completed=true;localStorage.setItem(app.storageKey,JSON.stringify(draft));return {key:app.storageKey,year:draft.profile.year,invoices:draft.ledger.invoices.length};});await page.reload({waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());const restored=await page.evaluate(()=>({state:globalThis.ForfettarioPersonalApp.getState(),shell:!document.getElementById('appShell').hidden}));assert.equal(restored.shell,true);assert.equal(restored.state.profile.year,persistence.year);assert.equal(restored.state.ledger.invoices.length,persistence.invoices);assert.equal(persistence.key,'forfettarioProLocalV6Phase5');
  await page.locator('#workspaceNav [data-view="forecast"]').click();await page.locator('#simpleForecast').fill('5000');await page.waitForTimeout(50);assert.equal(await page.locator('#simpleForecast').inputValue(),'5000');await page.locator('#saveForecast').click();await page.waitForFunction(()=>globalThis.ForfettarioPersonalApp.getState().forecast.expectedReceiptsCents===500000);assert.equal((await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState())).forecast.expectedReceiptsCents,500000);
  assert.equal(server.apiRequests[0].url,'/api/stato');assert.ok(server.apiRequests.some(item=>item.url==='/api/forfettario/config'));assert.deepEqual(consoleErrors,[]);assert.deepEqual(pageErrors,[]);assert.deepEqual(external,[]);assert.deepEqual(server.missing,[]);await context.close();
});

test('Forfettario 11C: matrice previdenziale authoritative completa e renderer UI',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1024,height:768}}),page=await context.newPage(),errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());const base=await page.evaluate(()=>globalThis.ForfettarioPersonalApp.loadDemo());
  const calculated=configEnvelope().result.pensionManagements.flatMap(management=>management.years.filter(year=>year.status==='CALCOLABILE').map(year=>({id:management.id,year:year.year,requiredFacts:year.requiredFacts}))),completeOptions={INPS_GS:{otherMandatoryCoverage:false},INPS_ARTIGIANI:{ageRateProfile:'adult',contributionHistory:'post1995',reductionMode:'none'},INPS_COMMERCIANTI:{ageRateProfile:'adult',contributionHistory:'post1995',reductionMode:'none'},ENASARCO:{mandateType:'mono'},CNPADC:{subjectiveRateBps:1200,minimumProfile:'ordinary'},CNPR:{subjectiveRateBps:1500,subjectiveMinimumMode:'full',supplementaryMinimumMode:'full',integrativeMinimumApplies:true},CASSA_GEOMETRI:{minimumProfile:'ordinary'},ENPACL:{rateProfile:'ordinary'},ENPAP:{subjectiveRateBps:1000,subjectiveMinimumCents:85600},EPAP:{subjectiveRateBps:1000,minimumProfile:'ordinary'},INPGI_GS:{minimumProfile:'ordinary'}};assert.equal(calculated.length,15);
  for(const row of calculated){const inspected=await page.evaluate(({row,base,options})=>{const app=globalThis.ForfettarioPersonalApp,source=JSON.parse(JSON.stringify(base));source.profile.year=row.year;source.profile.pension={managementId:row.id,options:{}};const missing=app.pensionContractAudit(source),ui=app.pensionUiAudit(source);source.profile.pension.options=options;const complete=app.pensionContractAudit(source),completeUi=app.pensionUiAudit(source),payload=app.buildCalculationPayload(source);return {missing,ui,complete,completeUi,payload};},{row,base,options:completeOptions[row.id]});const initialFacts=row.requiredFacts.filter(item=>!item.requiredWhen).map(item=>item.id),applicable=row.requiredFacts.filter(item=>!item.requiredWhen||item.requiredWhen.values.includes(completeOptions[row.id][item.requiredWhen.factId]));assert.equal(inspected.missing.completeness.complete,false,`${row.id} ${row.year}: incompleto senza fatti`);assert.deepEqual(inspected.ui.factIds,initialFacts,`${row.id} ${row.year}: controlli renderer`);assert.equal(inspected.complete.completeness.complete,true,`${row.id} ${row.year}: completo`);assert.match(inspected.completeUi.text,/Gestione confermata/);assert.doesNotMatch(inspected.completeUi.text,/new2025_50|newEntrant50|forfettario35|\bnone\b/);for(const specification of applicable.filter(item=>item.domain.type==='enum')){const control=inspected.completeUi.controls.find(item=>item.factId===specification.id);assert.ok(control,`${row.id} ${row.year} ${specification.id}: select presente`);assert.deepEqual(control.values,specification.domain.allowedValues,`${row.id} ${row.year} ${specification.id}: dominio UI authoritative`);}for(const specification of applicable.filter(item=>item.domain.type==='integer'&&!(row.id==='CNPADC'&&item.id==='subjectiveRateBps'))){const control=inspected.completeUi.controls.find(item=>item.factId===specification.id),scale=100;assert.ok(control,`${row.id} ${row.year} ${specification.id}: input presente`);if(Array.isArray(specification.domain.allowedValues))assert.deepEqual(control.values,specification.domain.allowedValues.map(String),`${row.id} ${row.year} ${specification.id}: allowedValues UI authoritative`);else{assert.equal(control.min,String(specification.domain.min/scale));assert.equal(control.max,String(specification.domain.max/scale));assert.equal(control.step,String((specification.domain.step||1)/scale));}}assert.equal(inspected.payload.status,'calculated');assert.deepEqual(Object.keys(inspected.payload.payload.pensionFacts.options).sort(),applicable.map(item=>item.id).sort(),`${row.id} ${row.year}: payload limitato ai fact dichiarati`);}

  const unsupportedCases=[
    {id:'INPS_ARTIGIANI',year:2025,options:{ageRateProfile:'under21',contributionHistory:'post1995',reductionMode:'none'}},
    {id:'CASSA_GEOMETRI',year:2026,options:{minimumProfile:'no_minima'}},
    {id:'ENPACL',year:2026,options:{rateProfile:'reduced',reductionEligibilityConfirmed:false}},
    {id:'EPAP',year:2025,options:{subjectiveRateBps:1000,minimumProfile:'no_minima'}},
    {id:'INPGI_GS',year:2025,options:{minimumProfile:'no_minima'}}
  ];
  for(const sample of unsupportedCases){const inspected=await page.evaluate(({sample,base})=>{const app=globalThis.ForfettarioPersonalApp,source=JSON.parse(JSON.stringify(base));source.profile.year=sample.year;source.profile.startDate=`${sample.year}-01-10`;source.profile.pension={managementId:sample.id,options:sample.options};return {contract:app.pensionContractAudit(source),ui:app.pensionUiAudit(source)};},{sample,base});assert.equal(inspected.contract.completeness.complete,false,`${sample.id}: non definitivo`);assert.equal(inspected.contract.completeness.unsupported,true,`${sample.id}: configurazione reale non calcolabile`);assert.deepEqual(inspected.contract.completeness.missingFacts,[],`${sample.id}: nessun fatto falsamente mancante`);assert.match(inspected.ui.text,/valido|profilo|requisiti|verifica esterna|calcol/i,`${sample.id}: informazione comprensibile`);assert.doesNotMatch(inspected.ui.text,/Informazioni ancora necessarie/,`${sample.id}: nessuna falsa CTA`);}

  const invalid=await page.evaluate(base=>{const app=globalThis.ForfettarioPersonalApp,source=JSON.parse(JSON.stringify(base));source.profile.year=2025;source.profile.pension={managementId:'CNPADC',options:{subjectiveRateBps:1100,minimumProfile:'ordinary',professionalNote:'NON_INVIARE'}};const cnpadc=app.pensionContractAudit(source),payload=app.buildCalculationPayload(source);source.profile.pension={managementId:'ENPAP',options:{subjectiveRateBps:1000,subjectiveMinimumCents:1}};return {cnpadc,payload,enpap:app.pensionContractAudit(source)};},base);assert.equal(invalid.cnpadc.completeness.complete,false);assert.equal(invalid.cnpadc.completeness.unsupported,false);assert.ok(invalid.cnpadc.completeness.missingFacts.includes('subjectiveRateBps'));assert.equal(invalid.enpap.completeness.complete,false);assert.equal(invalid.enpap.completeness.unsupported,false);assert.ok(invalid.enpap.completeness.missingFacts.includes('subjectiveMinimumCents'));assert.equal(JSON.stringify(invalid.payload).includes('NON_INVIARE'),false,'campi estranei esclusi dal payload');
  const resolution=await page.evaluate(()=>globalThis.ForfettarioPersonalApp.diagnosticResolutionAudit());assert.equal(resolution.deadEnds,0);assert.equal(resolution.falseCtas,0);assert.ok(resolution.rows.some(item=>item.code==='PENSION_CONFIGURATION_NOT_CALCULABLE'&&item.category==='external'&&!item.action));
  for(const row of [{id:'INARCASSA',year:2025},{id:'CASSA_FORENSE',year:2026},{id:'EPPI',year:2025},{id:'ENPAF',year:2026}]){const inspected=await page.evaluate(({row,base})=>{const app=globalThis.ForfettarioPersonalApp,source=JSON.parse(JSON.stringify(base));source.profile.year=row.year;source.profile.pension={managementId:row.id,options:{}};return {audit:app.pensionContractAudit(source),ui:app.pensionUiAudit(source)};},{row,base});assert.equal(inspected.audit.completeness.unsupported,true,`${row.id} ${row.year}`);assert.equal(inspected.ui.factIds.length,0);assert.match(inspected.ui.text,/verifica esterna/i);}
  assert.deepEqual(errors,[]);await context.close();
});

test('Forfettario 11C: risposte sequenziali preservano lo scroll a 1024 e 390 px',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  for(const viewport of [{width:1024,height:768},{width:390,height:844}]){const context=await browser.newContext({locale:'it-IT',viewport}),page=await context.newPage(),errors=[];page.setDefaultTimeout(5000);page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());await page.locator('#choosePersonal').click();await page.locator('#setupStartDate').fill('2025-01-10');await page.locator('#atecoQuery').fill('grafico');await page.waitForFunction(()=>document.querySelectorAll('#atecoResults [data-ateco-code]').length>0);await page.locator('#atecoResults [data-ateco-code]').first().click();await page.locator('#onboardNext').click();
    await page.locator('[data-answer-name="noListedSituations"][data-answer-value="false"]').press('Space');await page.waitForTimeout(80);for(const [name,value] of [['residenceOutside','true'],['vatSpecial','false'],['partnership','true']]){const button=page.locator(`[data-answer-name="${name}"][data-answer-value="${value}"]`);await button.scrollIntoViewIfNeeded();const before=await page.evaluate(()=>scrollY);await button.press('Space');await page.waitForTimeout(80);const after=await page.evaluate(()=>scrollY);assert.ok(Math.abs(after-before)<=2,`${viewport.width}px ${name}: ${before} -> ${after}`);assert.equal(await page.locator(`[data-answer-name="${name}"][aria-pressed="true"]`).count(),1);}assert.deepEqual(errors,[]);await context.close();}
});

test('Forfettario 11: Persona A, ricerca naturale e requisiti senza risposte implicite',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());await page.locator('#choosePersonal').click();
  const blank=await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState());assert.equal(blank.profile.eligibilityFacts.vatSpecialRegimeAbsent,null);assert.equal(blank.profile.eligibilityFacts.employeeCostsCents,null);assert.equal(blank.profile.pension.managementId,null);
  await page.locator('#setupStartDate').fill('2025-01-10');
  for(const query of ['commercialista','grafico','parrucchiere','avvocato','avvocat','studi legali','consulenza informatica','idraulico','fotografo','psicologo']){await page.locator('#atecoQuery').fill(query);await page.waitForFunction(()=>document.querySelectorAll('#atecoResults [data-ateco-code]').length>0);assert.ok(await page.locator('#atecoResults [data-ateco-code]').count()>0,query);}
  await page.locator('#atecoQuery').fill('a');assert.equal((await page.locator('#atecoResults').innerText()).trim(),'Scrivi almeno 2 caratteri.');await page.locator('#atecoQuery').fill('commercialista');await page.waitForFunction(()=>document.querySelectorAll('#atecoResults [data-ateco-code]').length>0);await page.locator('#atecoResults [data-ateco-code]').first().click();await page.waitForFunction(()=>document.querySelectorAll('#activityDraftList .selected-activity').length===1);assert.match(await page.locator('#activityDraftList').innerText(),/attività selezionata/i);assert.match(await page.locator('#activityDraftList').innerText(),/rimuovi/i);
  await page.locator('#onboardNext').click();await page.waitForSelector('[data-answer-name="noListedSituations"]');assert.equal(await page.locator('[data-answer-name="noListedSituations"][aria-pressed="true"]').count(),0,'nessuna risposta annuale deve essere preselezionata');assert.deepEqual(errors,[]);await context.close();
});

test('Forfettario 11: Persona C, persistenza annuale e documenti a cavallo anno',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1280,height:960}}),page=await context.newPage(),errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());const prepared=await page.evaluate(async()=>{const app=globalThis.ForfettarioPersonalApp,draft=app.loadDemo(),clone=value=>JSON.parse(JSON.stringify(value));draft.demo=false;draft.mode='personal';draft.onboarding.completed=true;const y2026=clone(draft.fiscalYears['2026']),y2025=clone(y2026);y2026.year=2026;y2026.eligibilityFacts.employeeCostsCents=2600;y2026.forecast.expectedReceiptsCents=260000;y2026.forecast.expectedDate='2026-12-31';y2025.year=2025;y2025.eligibilityFacts.employeeCostsCents=2500;y2025.forecast.expectedReceiptsCents=250000;y2025.forecast.expectedDate='2025-12-31';draft.fiscalYears={'2025':y2025,'2026':y2026};draft.profile.year=2026;const paid=draft.ledger.invoices.find(invoice=>draft.ledger.payments.some(payment=>payment.invoiceId===invoice.id)),future=draft.ledger.invoices.find(invoice=>invoice.id!==paid.id);paid.issueDate='2025-12-20';draft.ledger.payments.filter(payment=>payment.invoiceId===paid.id).forEach(payment=>payment.cashDate='2026-01-15');future.issueDate='2026-02-10';draft.ledger.payments=draft.ledger.payments.filter(payment=>payment.invoiceId!==future.id);draft.ledger.allocations=draft.ledger.allocations.filter(allocation=>draft.ledger.payments.some(payment=>payment.id===allocation.paymentId));const result=await app.restore(JSON.stringify({format:'forfettario-pro-backup-v1',exportedAt:new Date().toISOString(),state:draft}));return {result,paid:paid.number,future:future.number};});assert.equal(prepared.result.ok,true,JSON.stringify(prepared.result));
  await page.selectOption('#contextYear','2025');await page.locator('#confirmConfirmation').click();await page.waitForFunction(()=>globalThis.ForfettarioPersonalApp.getState().profile.year===2025);await page.reload({waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config()&&!document.getElementById('appShell').hidden);let annual=await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState());assert.equal(annual.profile.year,2025);assert.equal(annual.profile.eligibilityFacts.employeeCostsCents,2500);assert.equal(annual.forecast.expectedReceiptsCents,250000);
  await page.locator('#workspaceNav [data-view="invoices"]').click();let invoices=(await page.locator('#viewInvoices').innerText()).replace(/\s+/g,' ');assert.match(invoices,new RegExp(prepared.paid.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(invoices,new RegExp(prepared.future.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(invoices,/Documento 2025/);
  await page.selectOption('#contextYear','2026');await page.locator('#confirmConfirmation').click();await page.waitForFunction(()=>globalThis.ForfettarioPersonalApp.getState().profile.year===2026);annual=await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState());assert.equal(annual.profile.eligibilityFacts.employeeCostsCents,2600);assert.equal(annual.forecast.expectedReceiptsCents,260000);invoices=(await page.locator('#viewInvoices').innerText()).replace(/\s+/g,' ');assert.match(invoices,/Documento 2025 · movimento nel 2026/);assert.match(invoices,new RegExp(prepared.future.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.deepEqual(errors,[]);await context.close();
});

test('Forfettario 11: Persona B, saldo acconti e cambio area non distruttivo',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1100,height:900}}),page=await context.newPage(),errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());await page.locator('#loadDemoStart').click();await page.waitForFunction(()=>!document.getElementById('appShell').hidden);
  await page.locator('#workspaceNav [data-view="tax"]').click();await page.locator('#openTaxPlanning').click();await page.locator('#priorTax').fill('1000');await page.locator('#advancesPaid').fill('400');await page.locator('#credits').fill('25');await page.locator('#saveTaxPlanning').click();await page.waitForFunction(()=>!document.getElementById('taxPlanningModal').classList.contains('open'));const summary=(await page.locator('#taxPlanningSummary').innerText()).replace(/\s+/g,' ');assert.match(summary,/1\.000,00\s*€/);assert.match(summary,/400,00\s*€/);assert.match(summary,/25,00\s*€/);assert.match(await page.locator('#openTaxPlanning').innerText(),/modifica/i);
  const before=await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState()));await page.locator('#switchArea').click();await page.waitForFunction(()=>!document.getElementById('startFlow').hidden);assert.equal(await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState())),before);await page.locator('#choosePersonal').click();await page.waitForFunction(()=>!document.getElementById('appShell').hidden);assert.equal(await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState())),before);assert.deepEqual(errors,[]);await context.close();
});

test('Forfettario 11: Persona D, portafoglio professionale e azioni mobile',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());const transfers=await page.evaluate(()=>{const personal=globalThis.ForfettarioPersonalApp,professional=globalThis.ForfettarioProfessionalApp,base=personal.loadDemo();return Array.from({length:3},(_,index)=>{const draft=JSON.parse(JSON.stringify(base));draft.demo=false;draft.profile.taxCode=String(index+1).padStart(11,'0');draft.profile.vatCode=String(10000000001+index);if(index===1){draft.profile.pension={managementId:null,options:{}};draft.fiscalYears['2026'].pension={managementId:null,options:{}};}return professional.createTransfer(draft,`Cliente Persona D ${index+1}`);});});await page.reload({waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());await page.locator('#chooseProfessional').click();await page.waitForFunction(()=>!document.getElementById('appShell').hidden&&document.getElementById('proViewDashboard').classList.contains('active'));
  for(const [index,transfer] of transfers.entries()){await page.locator('#practiceImportTop').setInputFiles({name:`persona-d-${index+1}.json`,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(transfer))});await page.waitForFunction(()=>document.getElementById('professionalPreviewModal').classList.contains('open'));await page.locator('#confirmProfessionalPreview').click();await page.waitForFunction(()=>!document.getElementById('professionalPreviewModal').classList.contains('open'));}
  await page.locator('#workspaceNav [data-pro-view="clients"]').click();await page.waitForFunction(()=>document.querySelectorAll('#proClientTableBody tr').length===3);assert.equal(await page.locator('#proClientTableBody tr').count(),3);await page.waitForFunction(()=>/DA COMPLETARE/i.test([...document.querySelectorAll('#proClientTableBody tr')].find(row=>row.textContent.includes('Cliente Persona D 2'))?.textContent||''));assert.equal(server.apiRequests.filter(item=>item.url==='/api/forfettario/calcola'&&/"managementId":null/.test(item.body)).length,0,'la pratica incompleta non attraversa il confine Worker');assert.doesNotMatch(await page.locator('#proIssueList').innerText().catch(()=>''),/[A-Z_]{4,}/);
  await page.setViewportSize({width:390,height:860});assert.equal(await page.locator('#proClientCards').isVisible(),true);const firstCard=page.locator('#proClientCards .pro-client-card').first();assert.equal(await firstCard.locator(':scope > .pro-actions > .btn, :scope > .pro-client-actions > .btn, :scope > div > .btn').count()>=1,true);assert.match(await firstCard.innerText(),/apri/i);await firstCard.locator('details.pro-action-menu summary').click();assert.match(await firstCard.innerText(),/note/i);assert.match(await firstCard.innerText(),/archivia/i);assert.equal(await page.locator('#proFilterToggle').isVisible(),true);await page.locator('#proFilterToggle').click();await page.selectOption('#proYearFilter','2026');assert.match(await page.locator('#proFilterCount').innerText(),/1 attivo/i);const geometry=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,tableVisible:!!document.querySelector('.pro-client-table')&&getComputedStyle(document.querySelector('.pro-client-table')).display!=='none'}));assert.ok(geometry.overflow<=1);assert.equal(geometry.tableVisible,false);assert.deepEqual(errors,[]);await context.close();
});

test('Forfettario 10B: layout reale senza overflow a 1440, 1280, 1100, 1024, 390 e 375 px',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  for(const width of [1440,1280,1100,1024,390,375]){const context=await browser.newContext({locale:'it-IT',viewport:{width,height:920}}),page=await context.newPage(),errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());const landing=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,visible:!document.getElementById('startFlow').hidden}));assert.equal(landing.visible,true);assert.ok(landing.overflow<=1,`landing ${width}px`);const menu=page.locator('#startFlow .tal-gh-menu-toggle'),nav=page.locator('#talGhNavStart');if(width<=760){assert.equal(await menu.isVisible(),true,`toggle visibile a ${width}px`);await menu.click();assert.equal(await nav.isVisible(),true,`menu aperto a ${width}px`);await menu.click();}else{assert.equal(await menu.isVisible(),false,`nessun toggle inattivo a ${width}px`);assert.equal(await nav.isVisible(),true,`navigazione visibile a ${width}px`);}await page.locator('#loadDemoStart').click();await page.waitForFunction(()=>!document.getElementById('appShell').hidden&&globalThis.ForfettarioAuthoritative.diagnostics().hasResult);const app=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,dashboard:document.getElementById('viewDashboard').classList.contains('active'),footer:!!document.querySelector('#appShell .tal-site-footer'),metricWidths:[...document.querySelectorAll('#dashboardMetrics .card')].map(card=>card.getBoundingClientRect().width),clipped:[...document.querySelectorAll('#personalSessionActions button')].some(button=>button.scrollWidth>button.clientWidth+1)}));assert.equal(app.dashboard,true);assert.equal(app.footer,true);assert.ok(app.overflow<=1,`app ${width}px`);assert.equal(app.clipped,false,`azioni non troncate a ${width}px`);assert.ok(app.metricWidths.every(value=>value>120),`metriche leggibili a ${width}px`);assert.deepEqual(errors,[]);await context.close();}
});

test('Forfettario hardening: calendario, denaro, diagnostica, selezioni e conferme TAL',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1440,height:1000}}),page=await context.newPage(),nativeDialogs=[],errors=[];
  await page.addInitScript(()=>{const NativeDate=Date;let clock='2026-09-13T12:00:00.000Z';globalThis.__setForfettarioTestDate=value=>{clock=value;};class TestDate extends NativeDate{constructor(...args){super(...(args.length?args:[clock]));}static now(){return new NativeDate(clock).getTime();}}TestDate.parse=NativeDate.parse;TestDate.UTC=NativeDate.UTC;globalThis.Date=TestDate;});
  page.on('dialog',dialog=>{nativeDialogs.push(dialog.type());dialog.dismiss();});page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());
  const restored=await page.evaluate(async()=>{const app=globalThis.ForfettarioPersonalApp,draft=app.loadDemo();draft.demo=false;draft.taxPlanning.priorYearTaxCents=50000;draft.fiscalYears['2026'].taxPlanning=JSON.parse(JSON.stringify(draft.taxPlanning));return app.restore(JSON.stringify({format:'forfettario-pro-backup-v1',exportedAt:new Date().toISOString(),state:draft}));});
  assert.equal(restored.ok,true,JSON.stringify(restored));await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.diagnostics().hasResult);

  await page.locator('#workspaceNav [data-view="tax"]').click();await page.waitForFunction(()=>document.getElementById('paymentTimeline').textContent.includes('1791'));
  const septemberTimeline=(await page.locator('#paymentTimeline').innerText()).replace(/\s+/g,' ');
  assert.match(septemberTimeline,/2026-11-30/);assert.match(septemberTimeline,/300,00\s*€/);assert.match(septemberTimeline,/codice 1791/);assert.match(septemberTimeline,/anno di riferimento 2026/);
  assert.match(septemberTimeline,/2027-11-30/);assert.match(septemberTimeline,/anno di riferimento 2027/);
  assert.doesNotMatch(septemberTimeline,/Nessun pagamento/);
  await page.evaluate(()=>globalThis.__setForfettarioTestDate('2026-11-30T12:00:00.000Z'));await page.locator('#workspaceNav [data-view="tax"]').click();assert.match((await page.locator('#paymentTimeline').innerText()).replace(/\s+/g,' '),/anno di riferimento 2026/,'la scadenza resta visibile nel giorno dovuto');
  await page.evaluate(()=>globalThis.__setForfettarioTestDate('2026-12-01T12:00:00.000Z'));await page.locator('#workspaceNav [data-view="tax"]').click();const decemberTimeline=(await page.locator('#paymentTimeline').innerText()).replace(/\s+/g,' ');assert.doesNotMatch(decemberTimeline,/anno di riferimento 2026/);assert.match(decemberTimeline,/anno di riferimento 2027/,'un evento 2027 conserva la propria annualità');
  await page.evaluate(()=>globalThis.__setForfettarioTestDate('2026-09-13T12:00:00.000Z'));

  await page.locator('#workspaceNav [data-view="invoices"]').click();const unpaidId=await page.evaluate(()=>{const s=globalThis.ForfettarioPersonalApp.getState(),paid=new Set(s.ledger.payments.map(item=>item.invoiceId));return s.ledger.invoices.find(item=>!paid.has(item.id)).id;});
  await page.locator(`[data-edit-invoice="${unpaidId}"]`).first().click();await page.locator('#invoiceAmount').fill('9500,25');await page.locator('#saveInvoice').click();await page.waitForFunction(()=>!document.getElementById('invoiceModal').classList.contains('open'));const moneyRow=(await page.locator(`tr:has([data-edit-invoice="${unpaidId}"])`).innerText()).replace(/\s+/g,' ');assert.match(moneyRow,/9\.500,25\s*€/);
  await page.locator('#workspaceNav [data-view="forecast"]').click();await page.locator('#simpleForecast').fill('9500,25');await page.locator('#simpleForecast').press('Tab');assert.equal(await page.locator('#simpleForecast').inputValue(),'9.500,25');await page.locator('#saveForecast').click();await page.waitForFunction(()=>globalThis.ForfettarioPersonalApp.getState().forecast.expectedReceiptsCents===950025);await page.waitForFunction(()=>document.getElementById('forecastMetrics').textContent.includes('9.500,25'));

  await page.locator('#workspaceNav [data-view="invoices"]').click();const paidId=await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState().ledger.payments[0].invoiceId),beforeOverpayment=await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState()));await page.locator(`[data-edit-invoice="${paidId}"]`).first().click();await page.locator('#invoiceAmount').fill('1,00');await page.locator('#saveInvoice').click();const overpayment=(await page.locator('#invoiceErrors').innerText()).replace(/\s+/g,' '),afterOverpayment=await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState()));assert.equal(afterOverpayment,beforeOverpayment,'il rifiuto non muta lo stato');assert.match(overpayment,/Non puoi ridurre la fattura/);assert.match(overpayment,/1,00\s*€/);assert.match(overpayment,/già incassati/);assert.match(overpayment,/Modifica prima gli incassi collegati/);assert.doesNotMatch(overpayment,/PAYMENT_OVERPAYMENT|Annualità 2025|Annualità 2026/);await page.locator('#invoiceModal [data-close="invoiceModal"]').first().click();

  await page.locator('#workspaceNav [data-view="profile"]').click();await page.locator('#editProfile').click();await page.locator('#onboardNext').click();await page.waitForSelector('.option-card');const optionSemantics=await page.locator('.option-card').evaluateAll(cards=>({allButtons:cards.every(card=>card.tagName==='BUTTON'),allPressed:cards.every(card=>/^(true|false)$/.test(card.getAttribute('aria-pressed')||'')),allNamed:cards.every(card=>!!card.textContent.trim())}));assert.deepEqual(optionSemantics,{allButtons:true,allPressed:true,allNamed:true});const firstOption=page.locator('.option-card').first();await firstOption.focus();await firstOption.press('Space');assert.ok(await page.locator('.option-card[aria-pressed="true"].selected').count()>0);

  await page.reload({waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config()&&!document.getElementById('appShell').hidden);const beforeCancel=await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState()));await page.locator('#newPosition').click();assert.equal(await page.locator('#confirmationModal').isVisible(),true);await page.waitForFunction(()=>document.activeElement.id==='cancelConfirmation');await page.keyboard.press('Escape');assert.equal(await page.locator('#confirmationModal').isVisible(),false);assert.equal(await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState())),beforeCancel);await page.waitForFunction(()=>document.activeElement.id==='newPosition');
  await page.selectOption('#contextYear','2025');assert.equal(await page.locator('#confirmationModal').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState().profile.year),2026,'annullare il cambio annualità non muta lo stato');assert.equal(await page.locator('#contextYear').inputValue(),'2026');await page.waitForFunction(()=>document.activeElement.id==='contextYear');
  await page.selectOption('#contextYear','2025');assert.equal(await page.locator('#confirmationModal').isVisible(),true);assert.match(await page.locator('#confirmConfirmation').innerText(),/2025/);await page.waitForFunction(()=>document.getElementById('confirmationModal').contains(document.activeElement));await page.locator('#confirmConfirmation').click();await page.waitForFunction(()=>globalThis.ForfettarioPersonalApp.getState().profile.year===2025);const storedYear=await page.evaluate(()=>JSON.parse(localStorage.getItem(globalThis.ForfettarioPersonalApp.storageKey)).profile.year);assert.equal(storedYear,2025,'la conferma persiste il cambio annualità');
  await page.locator('#newPosition').click();await page.locator('#confirmConfirmation').click();await page.waitForFunction(()=>!document.getElementById('startFlow').hidden);assert.equal(await page.evaluate(()=>localStorage.getItem(globalThis.ForfettarioPersonalApp.storageKey)),null);
  assert.deepEqual(nativeDialogs,[]);assert.deepEqual(errors,[]);await context.close();
});

test('Forfettario hardening: modal TAL contenute e navigabili a 390 e 375 px',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  for(const width of [390,375]){const context=await browser.newContext({locale:'it-IT',viewport:{width,height:820}}),page=await context.newPage(),dialogs=[];page.on('dialog',dialog=>{dialogs.push(dialog.type());dialog.dismiss();});await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());await page.locator('#loadDemoStart').click();await page.waitForFunction(()=>!document.getElementById('appShell').hidden);await page.selectOption('#contextYear','2025');await page.waitForFunction(()=>document.activeElement.id==='cancelConfirmation');const geometry=await page.locator('#confirmationModal .modal-card').evaluate(card=>{const rect=card.getBoundingClientRect();return {left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom,viewportWidth:innerWidth,viewportHeight:innerHeight,focusInside:card.closest('[role="dialog"]').contains(document.activeElement),overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(geometry.left>=0&&geometry.right<=geometry.viewportWidth,`${width}px horizontal modal bounds`);assert.ok(geometry.top>=0&&geometry.bottom<=geometry.viewportHeight,`${width}px vertical modal bounds`);assert.ok(geometry.overflow<=1,`${width}px no horizontal overflow`);assert.equal(geometry.focusInside,true);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.getElementById('confirmationModal').contains(document.activeElement)),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#confirmationModal').isVisible(),false);assert.deepEqual(dialogs,[]);await context.close();}
});
