import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile, stat } from 'node:fs/promises';
import { createServer } from 'node:http';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PAGE_PATH = path.join(ROOT, 'tools', 'forfettario', 'index.html');
const MIME = new Map([['.css','text/css; charset=utf-8'],['.html','text/html; charset=utf-8'],['.ico','image/x-icon'],['.js','text/javascript; charset=utf-8'],['.json','application/json; charset=utf-8'],['.png','image/png'],['.svg','image/svg+xml'],['.woff2','font/woff2']]);
const FATTURAPA_HASH = 'E14C3EFEC2A434DFF7505523CD494E0FC55318E8B3F61146643375643FC2D62D';
const SENTINELS = ['SENTINEL_NAME_10B','SENTINEL_CF_10B','SENTINEL_VAT_10B','SENTINEL_CLIENT_10B','SENTINEL_INVOICE_10B','SENTINEL_CUSTOMER_10B','SENTINEL_XML_10B','SENTINEL_NOTE_10B','SENTINEL_FILE_10B','SENTINEL_HASH_10B'];

const sha256 = value => createHash('sha256').update(value,'utf8').digest('hex').toUpperCase();
function scriptBody(source,id){const match=source.match(new RegExp(`<script id="${id}">\\r?\\n?([\\s\\S]*?)<\\/script>`));assert.ok(match,`blocco ${id} presente`);return match[1];}
const sum = values => values.reduce((total,value)=>total+value,0);
function configEnvelope(){
  const rows=[['INPS_GS','INPS Gestione Separata','CALCOLABILE'],['INPS_ARTIGIANI','INPS Artigiani','CALCOLABILE'],['INPS_COMMERCIANTI','INPS Commercianti','CALCOLABILE'],['CNPADC','Cassa Dottori Commercialisti','CALCOLABILE'],['INARCASSA','Inarcassa','PARZIALE'],['CASSA_GEOMETRI','Cassa Geometri','CALCOLABILE']];
  return {status:'calculated',result:{schemas:{calculation:'forfettario-calculation-v1',atecoResolution:'forfettario-ateco-resolution-v1'},supportedYears:[2025,2026],pensionManagements:rows.map(([id,label,status])=>({id,label,years:[2025,2026].map(year=>({year,status,requiredFacts:id==='INPS_GS'?['otherMandatoryCoverage']:[],source:'fixture contrattuale',rulePackId:`${id.toLowerCase()}-${year}-v1`}))})),rulePacks:[2025,2026].map(year=>({year,id:`it-forfettario-${year}-v1`})),atecoCatalogRelease:'ISTAT-ATECO-2025-2026-07-15',atecoCrosswalkRelease:'fixture-crosswalk'},diagnostics:[],engineVersion:'forfettario-test-worker-v1',rulePackId:null,pensionRulePackId:null,atecoCrosswalkRelease:'fixture-crosswalk'};
}
function outcome(year,value,diagnostics=[]){return {status:diagnostics.length?'blocked':'calculated',value:diagnostics.length?null:value,diagnostics,rulePackId:`it-forfettario-${year}-v1`,appliedRules:[]};}
function calculationEnvelope(payload){
  const coefficient=code=>code.startsWith('62.')?6700:7800;
  const byActivity=payload.activities.map(item=>({activityId:item.key,cashCents:item.fiscalCashCents,coefficientBps:coefficient(item.atecoCode),grossIncomeCents:Math.round(item.fiscalCashCents*coefficient(item.atecoCode)/10000)}));
  const grossIncomeCents=sum(byActivity.map(item=>item.grossIncomeCents)),taxableIncomeCents=Math.max(0,grossIncomeCents-payload.taxFacts.deductibleContributionsPaidCents),taxCents=Math.round(taxableIncomeCents*(payload.taxFacts.startupRateRequested?5:15)/100),socialCents=Math.round(grossIncomeCents/10);
  const actualCashCents=Math.max(0,sum(payload.activities.map(item=>item.thresholdCashCents))),expectedCashCents=sum([payload.forecast.expectedReceiptsCents,payload.forecast.newCompensationCents].filter(Number.isInteger)),forecastMissing=expectedCashCents>0&&!payload.forecast.activityKey;
  const eligibility=outcome(payload.year,{eligible:true,immediateExit:false,nextYearExit:false}),income=outcome(payload.year,{grossIncomeCents,deductibleContributionsCents:payload.taxFacts.deductibleContributionsPaidCents,taxableIncomeCents,byActivity}),social=outcome(payload.year,{totalCents:socialCents,components:{subjectiveCents:socialCents}}),tax=outcome(payload.year,{rateBps:payload.taxFacts.startupRateRequested?500:1500,taxCents});
  const advanceMissing=payload.taxFacts.priorYearTaxCents===null||payload.taxFacts.validAdvancesPaidCents===null,advanceTotal=payload.taxFacts.priorYearTaxCents||0,advanceRows=advanceTotal<=5165?[]:advanceTotal<25752?[{number:2,amountCents:advanceTotal,taxCode:'1791'}]:[{number:1,amountCents:Math.round(advanceTotal*.4),taxCode:'1790'},{number:2,amountCents:advanceTotal-Math.round(advanceTotal*.4),taxCode:'1791'}],advances=advanceMissing?outcome(payload.year,null,[{code:'ADVANCE_INPUTS_MISSING',message:'Completa saldo e acconti.'}]):outcome(payload.year,{balance:{debitCents:Math.max(0,taxCents-payload.taxFacts.validAdvancesPaidCents)},installments:advanceRows}),calendarEvents=advanceRows.map(item=>({date:item.number===2?`${payload.year}-11-30`:`${payload.year}-06-30`,entity:'ERARIO',code:item.taxCode,kind:item.number===2?'advance_second_or_single':'balance_or_first_advance',amountCents:item.amountCents,referenceYear:payload.year,status:'planned'}));
  if(payload.year===2026)calendarEvents.push({date:'2027-11-30',entity:'ERARIO',code:'1791',kind:'advance_second_or_single',amountCents:12345,referenceYear:2027,status:'planned'});
  const calendar=advanceMissing?outcome(payload.year,null,[{code:'CALENDAR_INPUTS_MISSING',message:'Completa saldo e acconti.'}]):outcome(payload.year,{events:calendarEvents});
  const forecast=forecastMissing?outcome(payload.year,null,[{code:'FORECAST_ACTIVITY_REQUIRED',message:'Scegli l’attività.'}]):outcome(payload.year,{actualCashCents,expectedCashCents,projectedCashCents:actualCashCents+expectedCashCents,expectedEvents:[]}),reserveCents=Math.max(0,taxCents+socialCents-payload.taxFacts.deductibleContributionsPaidCents-(payload.taxFacts.validAdvancesPaidCents||0)),projected=forecastMissing?{status:'blocked',diagnostics:forecast.diagnostics}:{status:'calculated',taxCents,socialCents,reserveCents,tax,social,diagnostics:[]};
  const result={eligibility,income,social,tax,advances,calendar,forecast,projected,paidContributionCents:payload.taxFacts.deductibleContributionsPaidCents,reserveCents,ateco:payload.activities.map(item=>({key:item.key,atecoCode:item.atecoCode,status:'calculated',value:{coefficientBps:coefficient(item.atecoCode),groupId:'FIXTURE'},diagnostics:[]}))};
  return {status:[advances,calendar,forecast].some(item=>item.status==='blocked')?'blocked':'calculated',result,diagnostics:[],engineVersion:'forfettario-test-worker-v1',rulePackId:`it-forfettario-${payload.year}-v1`,pensionRulePackId:`${payload.pensionFacts.managementId.toLowerCase()}-${payload.year}-v1`,atecoCrosswalkRelease:'fixture-crosswalk',calculationId:`fixture-${payload.year}`};
}
async function startServer(){
  const requests=[],apiRequests=[],missing=[];let failNext=false;
  const server=createServer(async(request,response)=>{
    try{
      const url=new URL(request.url,'http://127.0.0.1');
      if(url.pathname==='/__forfettario-race'){response.writeHead(200,{'content-type':'text/html; charset=utf-8'});response.end('<!doctype html><title>race</title>');return;}
      if(url.pathname.startsWith('/api/')){
        let body='';for await(const chunk of request)body+=chunk;apiRequests.push({method:request.method,url:request.url,headers:request.headers,body});
        const json=value=>{response.writeHead(200,{'content-type':'application/json; charset=utf-8'});response.end(JSON.stringify(value));};
        if(url.pathname==='/api/stato')return json({ok:true});
        if(url.pathname==='/api/forfettario/config')return json(configEnvelope());
        if(url.pathname==='/api/forfettario/ateco/risolvi'){const payload=JSON.parse(body);return json({status:'calculated',result:{coefficientBps:payload.atecoCode.startsWith('62.')?6700:7800,groupId:'FIXTURE'},diagnostics:[],engineVersion:'forfettario-test-worker-v1',rulePackId:`it-forfettario-${payload.year}-v1`,pensionRulePackId:null,atecoCrosswalkRelease:'fixture-crosswalk'});}
        if(url.pathname==='/api/forfettario/calcola'){if(failNext){failNext=false;response.writeHead(503,{'content-type':'application/json'});return response.end('{}');}return json(calculationEnvelope(JSON.parse(body)));}
        response.writeHead(404).end('Not found');return;
      }
      let relative=decodeURIComponent(url.pathname).replace(/^\/+/,'');if(!relative||relative.endsWith('/'))relative+='index.html';const absolute=path.resolve(ROOT,relative);requests.push(relative);if(absolute!==ROOT&&!absolute.startsWith(`${ROOT}${path.sep}`)){response.writeHead(403).end('Forbidden');return;}await stat(absolute);response.writeHead(200,{'content-type':MIME.get(path.extname(absolute))||'application/octet-stream'});response.end(await readFile(absolute));
    }catch{missing.push(request.url);response.writeHead(404).end('Not found');}
  });
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
  return {baseUrl:`http://127.0.0.1:${server.address().port}`,requests,apiRequests,missing,failNext:()=>{failNext=true;},close:()=>new Promise(resolve=>server.close(resolve))};
}

test('Forfettario 10B: route contiene solo documenti locali e client authoritative',async()=>{
  const source=await readFile(PAGE_PATH,'utf8'),engine=scriptBody(source,'forfettario-engine-v6'),fatturaPa=scriptBody(source,'forfettario-fatturapa-import'),ui=scriptBody(source,'forfettario-tal-ui-v8');
  assert.match(source,/<meta name="robots" content="noindex,nofollow">/);assert.match(source,/\/assets\/tal-api-connection\.js/);assert.match(source,/\.\/authoritative-client\.js/);assert.match(source,/forfettario-calculation-v1/);assert.equal(sha256(fatturaPa),FATTURAPA_HASH);
  for(const forbidden of ['PENSION_PARAMETERS','PENSION_REGISTRY','ANNEX4_RULE_SETS','AtecoCrosswalkRelease','resolveAtecoCoefficient','calculateForfaitIncome','calculateSocialSecurity','calculateTax','calculateAdvancesAndBalance','calculateForecast','buildPaymentCalendar'])assert.doesNotMatch(source,new RegExp(forbidden));
  assert.match(engine,/ATECO_CATALOG_PACKED/);assert.doesNotMatch(source,/workers\.dev|localStorage[^\n]{0,120}(?:endpoint|apiUrl)|100% locale · nessun dato lascia/i);assert.doesNotMatch(source,/localStorage\.clear\s*\(/);assert.doesNotMatch(ui,/\b(?:alert|confirm|prompt)\s*\(|\.toFixed\s*\(/);assert.match(ui,/Intl\.NumberFormat\('it-IT'.*useGrouping:true/);assert.match(source,/id="confirmationModal"[^>]*role="dialog"[^>]*aria-modal="true"/);
});

test('Forfettario 10B: regressioni distribuite, privacy payload, race e reload',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1440,height:1000}}),page=await context.newPage(),consoleErrors=[],pageErrors=[],external=[];
  page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});page.on('pageerror',error=>pageErrors.push(error.message));page.on('request',request=>{if(new URL(request.url()).origin!==server.baseUrl)external.push(request.url());});page.on('dialog',dialog=>{pageErrors.push(`Native dialog inatteso: ${dialog.type()}`);dialog.dismiss();});
  await page.goto(`${server.baseUrl}/tools/forfettario/?forfettario-engine-tests=1&forfettario-fatturapa-tests=1`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.__FORFETTARIO_ENGINE_TEST_RESULT__&&globalThis.__FORFETTARIO_FATTURA_PA_TEST_RESULT__||globalThis.__FORFETTARIO_FATTURAPA_TEST_RESULT__);
  await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());await page.evaluate(()=>globalThis.ForfettarioPersonalApp.loadDemo());await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.diagnostics().hasResult);
  const reports=await page.evaluate(async()=>({Below:globalThis.__FORFETTARIO_ENGINE_TEST_RESULT__,fatturaPa:globalThis.__FORFETTARIO_FATTURAPA_TEST_RESULT__,personal:globalThis.ForfettarioPersonalApp.runBrowserRegressions(),professional:await globalThis.ForfettarioProfessionalApp.runBrowserRegressions()}));reports.engine=reports.Below;delete reports.Below;
  assert.deepEqual(Object.fromEntries(Object.entries(reports).map(([name,report])=>[name,`${report.passed}/${report.total}`])),{fatturaPa:'80/80',personal:'78/78',professional:'36/36',engine:'70/70'});assert.equal(Object.values(reports).reduce((n,r)=>n+r.failed,0),0);
  const privacy=await page.evaluate(async sentinels=>{const app=globalThis.ForfettarioPersonalApp,draft=app.loadDemo();Object.assign(draft,{clientId:sentinels[3],practiceId:sentinels[3]+'-P',professionalNote:sentinels[7]});draft.profile.name=sentinels[0];draft.profile.taxCode=sentinels[1];draft.profile.vatCode=sentinels[2];Object.assign(draft.ledger.invoices[0],{number:sentinels[4],customer:sentinels[5],xml:sentinels[6]});draft.ledger.invoices[0].origin={type:'FatturaPA',fileName:sentinels[8],contentHash:sentinels[9]};const built=app.buildCalculationPayload(draft);await globalThis.ForfettarioAuthoritative.schedule(built.payload);return {built,diagnostics:globalThis.ForfettarioAuthoritative.diagnostics()};},SENTINELS);
  assert.equal(privacy.built.status,'calculated');assert.equal(privacy.diagnostics.hasResult,true);
  const transport=server.apiRequests.map(item=>`${item.url}\n${JSON.stringify(item.headers)}\n${item.body}`).join('\n');for(const sentinel of SENTINELS)assert.equal(transport.includes(sentinel),false,`sentinella esclusa: ${sentinel}`);
  const posts=server.apiRequests.filter(item=>item.url==='/api/forfettario/calcola'),body=posts.map(item=>item.body).join('\n');assert.doesNotMatch(body,/personalState|invoices|payments|allocations|customer|taxCode|vatCode|fileName|contentHash|xml/i);
  const payload=JSON.parse(posts.at(-1).body);assert.deepEqual(Object.keys(payload).sort(),['activities','eligibilityFacts','forecast','pensionFacts','schema','taxFacts','year']);assert.ok(payload.activities.every(item=>/^A\d+$/.test(item.key)));
  const clientSource=await readFile(path.join(ROOT,'tools','forfettario','authoritative-client.js'),'utf8'),racePage=await context.newPage();await racePage.goto(`${server.baseUrl}/__forfettario-race`);await racePage.evaluate(()=>{globalThis.TAL_API={invalidate(){},async request(_path,options){const payload=JSON.parse(options.body),slow=payload.marker==='old';await new Promise((resolve,reject)=>{const timer=setTimeout(resolve,slow?80:5);options.signal?.addEventListener('abort',()=>{clearTimeout(timer);reject(new DOMException('aborted','AbortError'));},{once:true});});return new Response(JSON.stringify({status:'calculated',result:{marker:payload.marker},diagnostics:[],engineVersion:'race-v1',rulePackId:'race-pack'}),{status:200,headers:{'content-type':'application/json'}});}};});await racePage.addScriptTag({content:clientSource});const race=await racePage.evaluate(async()=>{const first={marker:'old'},second={marker:'new'},one=globalThis.ForfettarioAuthoritative.schedule(first),two=globalThis.ForfettarioAuthoritative.schedule(second);await Promise.allSettled([one,two]);const result={first:globalThis.ForfettarioAuthoritative.snapshot(first).status,second:globalThis.ForfettarioAuthoritative.snapshot(second)};globalThis.TAL_API.request=async()=>new Response('{}',{status:503,headers:{'content-type':'application/json'}});const failed={marker:'failed'};await globalThis.ForfettarioAuthoritative.schedule(failed);result.failed=globalThis.ForfettarioAuthoritative.snapshot(failed);return result;});await racePage.close();assert.equal(race.first,'stale');assert.equal(race.second.status,'calculated',JSON.stringify(race));assert.equal(race.second.result.marker,'new');assert.equal(race.failed.status,'error');assert.equal(race.failed.result,null);assert.equal(race.failed.diagnostics[0].message,'Il servizio di calcolo non è temporaneamente disponibile. I tuoi dati locali non sono stati persi.');
  const persistence=await page.evaluate(()=>{const app=globalThis.ForfettarioPersonalApp,draft=app.loadDemo();draft.demo=false;draft.mode='personal';draft.onboarding.completed=true;localStorage.setItem(app.storageKey,JSON.stringify(draft));return {key:app.storageKey,year:draft.profile.year,invoices:draft.ledger.invoices.length};});await page.reload({waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());const restored=await page.evaluate(()=>({state:globalThis.ForfettarioPersonalApp.getState(),shell:!document.getElementById('appShell').hidden}));assert.equal(restored.shell,true);assert.equal(restored.state.profile.year,persistence.year);assert.equal(restored.state.ledger.invoices.length,persistence.invoices);assert.equal(persistence.key,'forfettarioProLocalV6Phase5');
  await page.locator('#workspaceNav [data-view="forecast"]').click();await page.locator('#simpleForecast').fill('5000');await page.waitForTimeout(50);assert.equal(await page.locator('#simpleForecast').inputValue(),'5000');await page.locator('#saveForecast').click();await page.waitForFunction(()=>globalThis.ForfettarioPersonalApp.getState().forecast.expectedReceiptsCents===500000);assert.equal((await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState())).forecast.expectedReceiptsCents,500000);
  assert.equal(server.apiRequests[0].url,'/api/stato');assert.ok(server.apiRequests.some(item=>item.url==='/api/forfettario/config'));assert.deepEqual(consoleErrors,[]);assert.deepEqual(pageErrors,[]);assert.deepEqual(external,[]);assert.deepEqual(server.missing,[]);await context.close();
});

test('Forfettario 10B: layout reale senza overflow a 1440, 390 e 375 px',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  for(const width of [1440,390,375]){const context=await browser.newContext({locale:'it-IT',viewport:{width,height:920}}),page=await context.newPage(),errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());const landing=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,visible:!document.getElementById('startFlow').hidden}));assert.equal(landing.visible,true);assert.ok(landing.overflow<=1,`landing ${width}px`);if(width<=390){const menu=page.locator('#startFlow .tal-gh-menu-toggle');await menu.click();assert.equal(await page.locator('#talGhNavStart').isVisible(),true);await menu.click();}await page.locator('#loadDemoStart').click();await page.waitForFunction(()=>!document.getElementById('appShell').hidden&&globalThis.ForfettarioAuthoritative.diagnostics().hasResult);const app=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,dashboard:document.getElementById('viewDashboard').classList.contains('active'),footer:!!document.querySelector('#appShell .tal-site-footer')}));assert.equal(app.dashboard,true);assert.equal(app.footer,true);assert.ok(app.overflow<=1,`app ${width}px`);assert.deepEqual(errors,[]);await context.close();}
});

test('Forfettario hardening: calendario, denaro, diagnostica, selezioni e conferme TAL',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  const context=await browser.newContext({locale:'it-IT',viewport:{width:1440,height:1000}}),page=await context.newPage(),nativeDialogs=[],errors=[];
  await page.addInitScript(()=>{const NativeDate=Date;let clock='2026-09-13T12:00:00.000Z';globalThis.__setForfettarioTestDate=value=>{clock=value;};class TestDate extends NativeDate{constructor(...args){super(...(args.length?args:[clock]));}static now(){return new NativeDate(clock).getTime();}}TestDate.parse=NativeDate.parse;TestDate.UTC=NativeDate.UTC;globalThis.Date=TestDate;});
  page.on('dialog',dialog=>{nativeDialogs.push(dialog.type());dialog.dismiss();});page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());
  const restored=await page.evaluate(async()=>{const app=globalThis.ForfettarioPersonalApp,draft=app.loadDemo();draft.demo=false;draft.taxPlanning.priorYearTaxCents=50000;draft.fiscalYears['2026'].taxPlanning=JSON.parse(JSON.stringify(draft.taxPlanning));return app.restore(JSON.stringify({format:'forfettario-pro-backup-v1',exportedAt:new Date().toISOString(),state:draft}));});
  assert.equal(restored.ok,true,JSON.stringify(restored));await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.diagnostics().hasResult);

  await page.locator('#workspaceNav [data-view="tax"]').click();await page.waitForFunction(()=>document.getElementById('paymentTimeline').textContent.includes('1791'));
  const septemberTimeline=(await page.locator('#paymentTimeline').innerText()).replace(/\s+/g,' ');
  assert.match(septemberTimeline,/2026-11-30/);assert.match(septemberTimeline,/300,00\s*€/);assert.match(septemberTimeline,/codice 1791/);assert.match(septemberTimeline,/anno di riferimento 2026/);
  assert.match(septemberTimeline,/2027-11-30/);assert.match(septemberTimeline,/anno di riferimento 2027/);
  assert.doesNotMatch(septemberTimeline,/Nessun pagamento/);
  await page.evaluate(()=>globalThis.__setForfettarioTestDate('2026-11-30T12:00:00.000Z'));await page.locator('#workspaceNav [data-view="tax"]').click();assert.match((await page.locator('#paymentTimeline').innerText()).replace(/\s+/g,' '),/anno di riferimento 2026/,'la scadenza resta visibile nel giorno dovuto');
  await page.evaluate(()=>globalThis.__setForfettarioTestDate('2026-12-01T12:00:00.000Z'));await page.locator('#workspaceNav [data-view="tax"]').click();const decemberTimeline=(await page.locator('#paymentTimeline').innerText()).replace(/\s+/g,' ');assert.doesNotMatch(decemberTimeline,/anno di riferimento 2026/);assert.match(decemberTimeline,/anno di riferimento 2027/,'un evento 2027 conserva la propria annualità');
  await page.evaluate(()=>globalThis.__setForfettarioTestDate('2026-09-13T12:00:00.000Z'));

  await page.locator('#workspaceNav [data-view="invoices"]').click();const unpaidId=await page.evaluate(()=>{const s=globalThis.ForfettarioPersonalApp.getState(),paid=new Set(s.ledger.payments.map(item=>item.invoiceId));return s.ledger.invoices.find(item=>!paid.has(item.id)).id;});
  await page.locator(`[data-edit-invoice="${unpaidId}"]`).first().click();await page.locator('#invoiceAmount').fill('9500,25');await page.locator('#saveInvoice').click();await page.waitForFunction(()=>!document.getElementById('invoiceModal').classList.contains('open'));const moneyRow=(await page.locator(`tr:has([data-edit-invoice="${unpaidId}"])`).innerText()).replace(/\s+/g,' ');assert.match(moneyRow,/9\.500,25\s*€/);
  await page.locator('#workspaceNav [data-view="forecast"]').click();await page.locator('#simpleForecast').fill('9500,25');await page.locator('#simpleForecast').press('Tab');assert.equal(await page.locator('#simpleForecast').inputValue(),'9.500,25');await page.locator('#saveForecast').click();await page.waitForFunction(()=>globalThis.ForfettarioPersonalApp.getState().forecast.expectedReceiptsCents===950025);await page.waitForFunction(()=>document.getElementById('forecastMetrics').textContent.includes('9.500,25'));

  await page.locator('#workspaceNav [data-view="invoices"]').click();const paidId=await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState().ledger.payments[0].invoiceId),beforeOverpayment=await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState()));await page.locator(`[data-edit-invoice="${paidId}"]`).first().click();await page.locator('#invoiceAmount').fill('1,00');await page.locator('#saveInvoice').click();const overpayment=(await page.locator('#invoiceErrors').innerText()).replace(/\s+/g,' '),afterOverpayment=await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState()));assert.equal(afterOverpayment,beforeOverpayment,'il rifiuto non muta lo stato');assert.match(overpayment,/Non puoi ridurre la fattura/);assert.match(overpayment,/1,00\s*€/);assert.match(overpayment,/già incassati/);assert.match(overpayment,/Modifica prima gli incassi collegati/);assert.doesNotMatch(overpayment,/PAYMENT_OVERPAYMENT|Annualità 2025|Annualità 2026/);await page.locator('#invoiceModal [data-close="invoiceModal"]').first().click();

  await page.locator('#workspaceNav [data-view="profile"]').click();await page.locator('#editProfile').click();await page.locator('#onboardNext').click();await page.waitForSelector('.option-card');const optionSemantics=await page.locator('.option-card').evaluateAll(cards=>({allButtons:cards.every(card=>card.tagName==='BUTTON'),allPressed:cards.every(card=>/^(true|false)$/.test(card.getAttribute('aria-pressed')||'')),allNamed:cards.every(card=>!!card.textContent.trim())}));assert.deepEqual(optionSemantics,{allButtons:true,allPressed:true,allNamed:true});const firstOption=page.locator('.option-card').first();await firstOption.focus();await firstOption.press('Space');assert.ok(await page.locator('.option-card[aria-pressed="true"].selected').count()>0);

  await page.reload({waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config()&&!document.getElementById('appShell').hidden);const beforeCancel=await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState()));await page.locator('#newPosition').click();assert.equal(await page.locator('#confirmationModal').isVisible(),true);await page.waitForFunction(()=>document.activeElement.id==='cancelConfirmation');await page.keyboard.press('Escape');assert.equal(await page.locator('#confirmationModal').isVisible(),false);assert.equal(await page.evaluate(()=>JSON.stringify(globalThis.ForfettarioPersonalApp.getState())),beforeCancel);await page.waitForFunction(()=>document.activeElement.id==='newPosition');
  await page.selectOption('#contextYear','2025');assert.equal(await page.locator('#confirmationModal').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>globalThis.ForfettarioPersonalApp.getState().profile.year),2026,'annullare il cambio annualità non muta lo stato');assert.equal(await page.locator('#contextYear').inputValue(),'2026');await page.waitForFunction(()=>document.activeElement.id==='contextYear');
  await page.selectOption('#contextYear','2025');assert.equal(await page.locator('#confirmationModal').isVisible(),true);assert.match(await page.locator('#confirmConfirmation').innerText(),/2025/);await page.waitForFunction(()=>document.getElementById('confirmationModal').contains(document.activeElement));await page.locator('#confirmConfirmation').click();await page.waitForFunction(()=>globalThis.ForfettarioPersonalApp.getState().profile.year===2025);const storedYear=await page.evaluate(()=>JSON.parse(localStorage.getItem(globalThis.ForfettarioPersonalApp.storageKey)).profile.year);assert.equal(storedYear,2025,'la conferma persiste il cambio annualità');
  await page.locator('#newPosition').click();await page.locator('#confirmConfirmation').click();await page.waitForFunction(()=>!document.getElementById('startFlow').hidden);assert.equal(await page.evaluate(()=>localStorage.getItem(globalThis.ForfettarioPersonalApp.storageKey)),null);
  assert.deepEqual(nativeDialogs,[]);assert.deepEqual(errors,[]);await context.close();
});

test('Forfettario hardening: modal TAL contenute e navigabili a 390 e 375 px',async t=>{
  const server=await startServer();let browser;t.after(async()=>{if(browser)await browser.close();await server.close();});browser=await chromium.launch({headless:true});
  for(const width of [390,375]){const context=await browser.newContext({locale:'it-IT',viewport:{width,height:820}}),page=await context.newPage(),dialogs=[];page.on('dialog',dialog=>{dialogs.push(dialog.type());dialog.dismiss();});await page.goto(`${server.baseUrl}/tools/forfettario/`,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.ForfettarioAuthoritative.config());await page.locator('#loadDemoStart').click();await page.waitForFunction(()=>!document.getElementById('appShell').hidden);await page.selectOption('#contextYear','2025');await page.waitForFunction(()=>document.activeElement.id==='cancelConfirmation');const geometry=await page.locator('#confirmationModal .modal-card').evaluate(card=>{const rect=card.getBoundingClientRect();return {left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom,viewportWidth:innerWidth,viewportHeight:innerHeight,focusInside:card.closest('[role="dialog"]').contains(document.activeElement),overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(geometry.left>=0&&geometry.right<=geometry.viewportWidth,`${width}px horizontal modal bounds`);assert.ok(geometry.top>=0&&geometry.bottom<=geometry.viewportHeight,`${width}px vertical modal bounds`);assert.ok(geometry.overflow<=1,`${width}px no horizontal overflow`);assert.equal(geometry.focusInside,true);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.getElementById('confirmationModal').contains(document.activeElement)),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#confirmationModal').isVisible(),false);assert.deepEqual(dialogs,[]);await context.close();}
});
