import {entryHero} from './product-ui.js';
export function authEntry({ access, loginEmail, brand, icon, esc, button, signup = false, setup = null, heroPaused = false }) {
  let content;
  const exit = '<button class="text-link auth-exit" type="button" data-action="auth-logout">Esci</button>';
  if (setup) content = setup + exit;
  else if (access.phase === 'check-email') content = '<h2 id="auth-title">Verifica email</h2><p>'+esc(access.message)+'</p>'+button('auth-login-mode','Torna ad Accedi');
  else if (access.phase === 'loading') content = '<h2 id="auth-title" tabindex="-1">Accesso in corso</h2><p role="status" aria-live="polite">Verifica dell’account…</p>';
  else if (access.phase === 'config-error') content = '<h2 id="auth-title">Preview da configurare</h2><p>'+esc(access.message)+'</p>';
  else if (access.phase === 'error') content = '<h2 id="auth-title" tabindex="-1">Accesso da verificare</h2><p role="alert">'+esc(access.message)+'</p>'+button('auth-retry','Riprova')+exit;
  else if (access.phase === 'empty') content = '<h2 id="auth-title" tabindex="-1">Il tuo profilo TAL non è ancora configurato</h2><p>Non ci sono posizioni disponibili per questo account. Rivolgiti a chi ti ha invitato.</p>'+button('auth-retry','Ricontrolla')+exit;
  else if (access.phase === 'choosing') content = `<h2 id="auth-title" tabindex="-1">Come vuoi entrare?</h2><div class="auth-choices">${access.contexts.map((c, index) => `<button class="auth-choice" type="button" data-action="auth-select" data-choice="${index}">${icon(c.context_type === 'personal' ? 'person' : 'briefcase')}<span><strong>${esc(c.context_type === 'personal' ? 'La mia attività' : c.label)}</strong><small>${c.context_type === 'personal' ? 'Gestisci la tua posizione personale' : 'Gestisci i clienti dello Studio'}</small></span>${icon('chevron')}</button>`).join('')}</div>${exit}`;
  else content = `<div class="auth-tabs"><button class="text-link" type="button" data-action="auth-login-mode" aria-pressed="${!signup}">Accedi</button><button class="text-link" type="button" data-action="auth-signup-mode" aria-pressed="${signup}">Registrati</button></div><h2 id="auth-title">${signup ? 'Crea il tuo account' : 'Accedi a TAL'}</h2><form id="${signup ? 'signup-form' : 'login-form'}"><div class="field"><label for="login-email">Email</label><input id="login-email" name="email" type="email" autocomplete="username" inputmode="email" autocapitalize="none" spellcheck="false" required value="${esc(loginEmail)}" aria-describedby="auth-error"></div><div class="field"><label for="login-password">Password</label><input id="login-password" name="password" type="password" autocomplete="${signup ? 'new-password' : 'current-password'}" ${signup ? 'minlength="12"' : ''} required aria-describedby="auth-error"></div><p class="error" id="auth-error" role="alert">${esc(access.message)}</p>${signup ? '<p class="small muted">Almeno 12 caratteri. Prima di entrare dovrai confermare la tua email.</p>' : ''}<button class="button" type="submit">${signup ? 'Registrati' : 'Accedi'}</button></form>`;
  const welcome=access.phase==='signed-out'&&!setup;
  return `<div class="entry auth-entry ${welcome?'product-entry':''}"><header class="entry-header">${brand()}<span class="demo-label">Ambiente di sviluppo · dati sintetici</span></header><main class="entry-main" id="main" tabindex="-1"><div class="entry-intro" data-hero-paused="${heroPaused}"><p class="eyebrow">Forfettario</p>${welcome?entryHero():'<h1 class="entry-title">La tua attività.<br><em>Il tuo Studio.</em></h1>'}<p class="entry-copy">Entrate, tasse e documenti. In autonomia o con il tuo commercialista.</p>${welcome?`<div class="hero-actions"><button class="button hero-access" type="button" data-action="auth-signup-mode" data-auth-focus>Registrati${icon('arrow')}</button><button class="text-link hero-motion" type="button" data-action="hero-motion" aria-pressed="${heroPaused}">${heroPaused?'Riprendi animazione':'Ferma animazione'}</button></div>`:''}</div><section class="auth-card" aria-labelledby="auth-title" aria-busy="${access.phase === 'loading'}">${content}</section></main><footer class="entry-footer"><span>Tax Automation Lab</span><span>Anteprima di sviluppo</span></footer></div>`;
}
