export function authEntry({ access, loginEmail, brand, icon, esc, button }) {
  let content;
  const exit = '<button class="text-link auth-exit" type="button" data-action="auth-logout">Esci</button>';
  if (access.phase === 'loading') content = '<h2 id="auth-title" tabindex="-1">Un momento…</h2><p role="status" aria-live="polite">Stiamo verificando il tuo accesso.</p>';
  else if (access.phase === 'config-error') content = '<h2 id="auth-title">Preview da configurare</h2><p>'+esc(access.message)+'</p>';
  else if (access.phase === 'error') content = '<h2 id="auth-title" tabindex="-1">Accesso da verificare</h2><p role="alert">'+esc(access.message)+'</p>'+button('auth-retry','Riprova')+exit;
  else if (access.phase === 'empty') content = '<h2 id="auth-title" tabindex="-1">Il tuo profilo TAL non è ancora configurato</h2><p>Non ci sono posizioni disponibili per questo account. Rivolgiti a chi ti ha invitato.</p>'+button('auth-retry','Ricontrolla')+exit;
  else if (access.phase === 'choosing') content = `<h2 id="auth-title" tabindex="-1">Come vuoi entrare?</h2><div class="auth-choices">${access.contexts.map((c, index) => `<button class="auth-choice" type="button" data-action="auth-select" data-choice="${index}">${icon(c.context_type === 'personal' ? 'person' : 'briefcase')}<span><strong>${esc(c.context_type === 'personal' ? 'La mia attività' : c.label)}</strong><small>${c.context_type === 'personal' ? 'Gestisci la tua posizione personale' : 'Gestisci i clienti dello Studio'}</small></span>${icon('chevron')}</button>`).join('')}</div>${exit}`;
  else content = `<h2 id="auth-title">Accedi a TAL</h2><form id="login-form"><div class="field"><label for="login-email">Email</label><input id="login-email" name="email" type="email" autocomplete="username" inputmode="email" autocapitalize="none" spellcheck="false" required value="${esc(loginEmail)}" aria-describedby="auth-error"></div><div class="field"><label for="login-password">Password</label><input id="login-password" name="password" type="password" autocomplete="current-password" required aria-describedby="auth-error"></div><p class="error" id="auth-error" role="alert">${esc(access.message)}</p><button class="button" type="submit">Accedi</button></form>`;
  return `<div class="entry auth-entry"><header class="entry-header">${brand()}<span class="demo-label">Ambiente di sviluppo · dati demo</span></header><main class="entry-main" id="main" tabindex="-1"><div><p class="eyebrow">Il tuo forfettario, più semplice</p><h1 class="entry-title">Il tuo lavoro,<br><em>con meno pensieri.</em></h1><p class="entry-copy">Entrate, tasse e documenti. Tutto al suo posto, insieme al tuo commercialista.</p></div><section class="auth-card" aria-labelledby="auth-title" aria-busy="${access.phase === 'loading'}">${content}</section></main><footer class="entry-footer"><span>Tax Automation Lab</span><span>Accesso reale · contenuti di esempio</span></footer></div>`;
}
