import {managementLabel,humanDiagnostic} from './workflow-view.js';
const states={complete:'Completo',confirm:'Da confermare',missing:'Dato mancante',unsupported:'Non supportato'};
export function declarationView({state,heading,button,esc,euro,studio=true,canConfirm=studio,linkedStudio=false,base=''}){
 const header=heading('Dichiarazione TAL','Redditi PF 2026 · periodo d’imposta 2025');
 if(state.phase!=='ready')return header+(state.phase==='loading'?'<p role="status" aria-busy="true">Aggiornamento della bozza…</p>':'<p role="alert">'+(state.phase==='forbidden'?'Questa posizione non è più disponibile.':state.error==='year'?'Il modello definitivo di questa annualità non è ancora disponibile.':'Bozza non disponibile. Riprova con i dati aggiornati.')+'</p>'+button('declaration-retry','Riprova'));
 const record=state.data,d=record.draft,w=d.workflow,money=n=>Number.isSafeInteger(n)?euro(n):'Da completare';
 const value=f=>f.value===null?'—':f.unit==='cents'?money(f.value):f.unit==='bps'?(f.value/100)+'%':typeof f.value==='boolean'?(f.value?'Sì':'No'):esc(f.value);
 const summary=[['Ricavi incassati',d.summary.receivedCents],['Reddito forfettario',d.summary.grossIncomeCents],['Contributi versati',d.summary.paidCents],['Contributi dedotti',d.summary.deductedCents]];
 const status=w?.state==='prepared'?'Dati TAL preparati':w?.state==='blocked'?'Dati da completare':'Da confermare';
 const reviewNotice=d.previousReview?'<p class="review-stale" role="status">'+(canConfirm?'Dati cambiati: rivedi le precedenti conferme. I valori conservati nel form non valgono per il calcolo corrente.':linkedStudio?'In attesa di riconferma dello Studio':'I dati sono cambiati. Rivedi le precedenti conferme.')+'</p>':'';
 const reviews=canConfirm?'<section class="declaration-review"><h2>'+((w?.actions?.length??1)>0?'Da confermare':'Verifiche confermate')+'</h2><div class="declaration-review-row"><div><strong>Perdite pregresse</strong><p>'+esc(d.fields.find(f=>f.id==='LM37.5')?.value===0?'Assenza confermata per questi dati.':'Verifica le eventuali perdite da riportare.')+'</p></div>'+button('declaration-losses',d.fields.find(f=>f.id==='LM37.5')?.value===0?'Rivedi conferma':'Conferma assenza')+'</div><div class="declaration-review-row"><div><strong>Acconti e crediti</strong><p>Gli importi registrati in Pagamenti sono gli stessi usati in Dichiarazione e Tasse.</p></div><a class="text-link" href="'+esc(base+'pagamenti')+'">Apri Pagamenti</a></div></section>':'';
 const detail=studio?'<details class="declaration-detail" data-declaration-detail="model"><summary>Dettaglio modello e provenienza</summary><p class="small">Importi TAL al centesimo e rappresentazione all’euro del modello.</p><div class="declaration-fields">'+d.fields.map(f=>'<article><div><strong>'+esc(f.label)+'</strong><small>'+esc(f.id)+' · '+esc(states[f.state])+'</small></div><div class="declaration-field-value"><strong>'+value(f)+'</strong>'+(f.unit==='cents'&&f.modelValue!==null?'<small>Modello: '+esc(f.modelValue)+' €</small>':'')+'</div>'+(f.reason?'<p class="small">'+esc(f.reason)+'</p>':'')+'<details><summary>Provenienza</summary><p class="small">'+esc(f.provenance.fact)+' · '+esc(f.provenance.ruleVersion||'Dato raccolto')+'</p><p class="small">Istruzioni '+esc(f.authority.source)+' · pagina '+esc(f.authority.page)+'</p>'+f.provenance.refs.map(r=>'<p class="small">'+esc(r.entity)+' · '+esc(r.id||'revisione '+r.revision)+'</p>').join('')+'</details></article>').join('')+'</div></details>':'';
 const audit=studio&&d.provenance?.review?'<details class="declaration-detail"><summary>Verifiche registrate</summary><p>'+ (d.reviewCurrent?'Riferite ai dati correnti.':'Storico: non valido per i dati correnti.')+'</p>'+Object.entries(d.provenance.review.facts).map(([key,v])=>'<p><strong>'+esc(key==='priorLossesNone'?'Perdite pregresse':'Acconti versati')+'</strong> · '+esc(v.reason)+' · '+esc(v.recordedAt||'')+'</p><p class="small">Autore '+esc(v.actorId)+' · valore precedente '+esc(v.previous??'non indicato')+'</p>').join('')+'</details>':'';
 const analytic='<details class="declaration-detail"><summary>Attività e previdenza</summary><div class="declaration-fields">'+d.activities.map(a=>'<article><strong>ATECO '+esc(a.ateco)+'</strong><p>'+money(a.cashCents)+' incassati · '+(Number.isInteger(a.coefficientBps)?a.coefficientBps/100+'%':'coefficiente da verificare')+'</p><p>Reddito '+money(a.incomeCents)+'</p></article>').join('')+'</div><div class="breakdown">'+d.pensions.map(o=>'<div><span>'+esc(managementLabel(o.managementId))+'</span><strong>'+money(o.dueCents)+'</strong><small>'+esc(o.rr?.state==='COMPLETE'?'Dati previdenziali riconciliati':'Raccordo previdenziale da verificare')+'</small></div>').join('')+'</div></details>';
 const issues=d.issues.filter(i=>i.code!=='REVIEW_STALE');
 return header+'<div class="declaration-page"><section class="declaration-summary"><div><p class="eyebrow">Imposta sui dati TAL</p><strong class="amount money">'+money(d.summary.taxCents)+'</strong><p>Non è un importo da versare.</p></div><div><strong>'+status+'</strong><p>'+d.counts.complete+' dati preparati'+(w?.actions?.length?' · '+w.actions.length+(w.actions.length===1?' conferma richiesta':' conferme richieste'):'')+'</p><small>Versione '+record.revision+'</small></div></section><h2>Preparato da TAL</h2><div class="breakdown declaration-totals">'+summary.map(([label,n])=>'<div><span>'+label+'</span><strong>'+money(n)+'</strong></div>').join('')+'</div>'+reviewNotice+reviews+(issues.length?'<section class="payment-checks"><h2>Da verificare</h2><ul>'+[...new Set(issues.map(i=>i.message))].map(m=>'<li>'+esc(studio?m:humanDiagnostic(m))+'</li>').join('')+'</ul></section>':'')+analytic+detail+audit+'<details class="declaration-detail"><summary>Fuori dal perimetro TAL</summary><p>Altri redditi, frontespizio completo e quadri non preparati da TAL richiedono verifiche separate. Questa sezione non impedisce l’utilizzo dei dati e degli F24 supportati.</p></details>'+(studio?'<div class="declaration-actions">'+button('declaration-json','Esporta bozza JSON','','button secondary')+button('declaration-print','Stampa bozza','','text-link')+'</div>':'')+'<p><a class="text-link" href="'+esc(base+'pagamenti')+'">Vai a Pagamenti</a></p><p class="small muted declaration-notice">Bozza di lavoro, non pronta all’invio. TAL non trasmette la dichiarazione.</p></div>';
}
