const states={complete:'Completo',confirm:'Da confermare',missing:'Dato mancante',unsupported:'Non supportato'};
export function declarationView({state,heading,button,esc,euro,studio=true}){
 const title=studio?'Bozza Redditi PF':'Dati per la dichiarazione';
 const header=heading(title,'Redditi PF 2026 · periodo d’imposta 2025');
 if(state.phase!=='ready')return header+(state.phase==='loading'?'<p role="status" aria-busy="true">Stiamo preparando la bozza con i dati aggiornati.</p>':
  '<p role="alert">'+(state.phase==='forbidden'?'Questa posizione non è più disponibile.':state.error==='year'?'Il modello definitivo di questa annualità non è ancora disponibile.':state.error==='conflict'?'I dati sono cambiati durante la preparazione. Riprova con la situazione aggiornata.':'La bozza non è disponibile. Nessuna versione precedente viene mostrata come aggiornata.')+'</p>'+button('declaration-retry','Riprova'));
 const record=state.data,d=record.draft,money=n=>Number.isSafeInteger(n)?euro(n):'Da completare',value=f=>f.value===null?'—':f.unit==='cents'?money(f.value):f.unit==='bps'?(f.value/100)+'%':typeof f.value==='boolean'?(f.value?'Sì':'No'):esc(f.value);
 const missing=d.fields.filter(f=>['missing','unsupported'].includes(f.state));
 const reviewEntries=Object.entries(d.provenance?.review?.facts||{});
 const audit=studio&&reviewEntries.length?'<details class="declaration-detail"><summary>Verifiche professionali registrate</summary><p class="small">'+(d.reviewCurrent?'Riferite ai dati correnti.':'Storico: queste verifiche non valgono automaticamente per i dati aggiornati.')+'</p>'+reviewEntries.map(([k,v])=>'<article><strong>'+esc(k==='priorLossesNone'?'Assenza di perdite pregresse':'Acconti versati')+'</strong><p class="small">'+esc(v.reason)+' · '+esc(v.recordedAt||'')+'</p><p class="small">Autore: '+esc(v.actorId)+' · Valore precedente: '+esc(v.previous===null||v.previous===undefined?'non indicato':v.previous)+' · Revisione '+esc(d.provenance.review.revision)+'</p></article>').join('')+'</details>':'';
 const summary=[['Ricavi incassati',d.summary.receivedCents],['Reddito forfettario',d.summary.grossIncomeCents],['Contributi versati',d.summary.paidCents],['Contributi dedotti',d.summary.deductedCents]];
 const professional=studio?'<div class="declaration-actions">'+button('declaration-json','Esporta bozza JSON')+'<button class="text-link" type="button" data-action="declaration-print">Stampa bozza</button></div>':'';
 const contributions=d.pensions.map(o=>'<div><span>'+esc(o.managementId.replaceAll('_',' '))+'</span><strong>'+money(o.dueCents)+'</strong><small>'+esc(o.state==='CALCULABLE'?'Calcolo TAL disponibile · raccordo dichiarativo da verificare':'Da completare/verificare')+'</small></div>').join('');
 const reviews=studio?'<section class="declaration-review"><h2>Conferme dello Studio</h2><p>Correggi entrate e contributi alla fonte. Qui puoi integrare soltanto i dati dichiarativi previsti.</p>'+
  '<div class="declaration-review-row"><div><strong>Perdite pregresse</strong><p>'+esc(d.fields.find(f=>f.id==='LM37.5')?.value===0?'Assenza confermata per questi dati.':'Verifica se esistono perdite da riportare. Non presumiamo che siano zero.')+'</p></div>'+
  button('declaration-losses',d.fields.find(f=>f.id==='LM37.5')?.value===0?'Rivedi conferma':'Conferma assenza')+'</div>'+
  (d.fields.find(f=>f.id==='LM45.2')?.provenance.fact==='Studio.lmAdvancesPaidCents'?'<div class="declaration-review-row"><div><strong>Acconti versati 2025</strong><p>Integra solo i versamenti dell’imposta sostitutiva verificati.</p></div>'+button('declaration-advances','Indica gli acconti')+'</div>':'')+'</section>':'';
 const detail=studio?'<details class="declaration-detail" data-declaration-detail="model"><summary>Dettaglio modello</summary><p class="small">Importi TAL al centesimo e rappresentazione all’euro prevista dal modello. Le differenze da riconciliare restano segnalate.</p><div class="declaration-fields">'+d.fields.map(f=>'<article><div><strong>'+esc(f.label)+'</strong><small>'+esc(f.id)+' · '+esc(states[f.state])+'</small></div><div class="declaration-field-value"><strong>'+value(f)+'</strong>'+(f.unit==='cents'&&f.modelValue!==null?'<small>Modello: '+esc(f.modelValue)+' €</small>':'')+'</div>'+(f.reason?'<p class="small">'+esc(f.reason)+'</p>':'')+'<details><summary>Provenienza</summary><p class="small">'+esc(f.provenance.fact)+'</p><p class="small">'+esc(f.provenance.ruleVersion||'Dato raccolto')+'</p><p class="small">Istruzioni '+esc(f.authority.source)+' · pagina '+esc(f.authority.page)+'</p>'+(f.provenance.refs.length?'<ul class="small">'+f.provenance.refs.map(r=>'<li>'+esc(r.entity)+' · '+esc(r.id||'revisione '+r.revision)+'</li>').join('')+'</ul>':'')+'</details></article>').join('')+'</div></details>':'';
 const analytic='<details class="declaration-detail" data-declaration-detail="activities"><summary>Attività e previdenza</summary>'+
  '<div class="declaration-fields">'+d.activities.map(a=>'<article><strong>ATECO '+esc(a.ateco)+'</strong><p>'+money(a.cashCents)+' incassati · '+(Number.isInteger(a.coefficientBps)?(a.coefficientBps/100)+'%':'coefficiente da verificare')+'</p><p class="small">Reddito '+money(a.incomeCents)+'</p></article>').join('')+'</div><div class="breakdown declaration-pensions">'+contributions+'</div></details>';
 return header+'<div class="declaration-page"><section class="declaration-summary"><div><p class="eyebrow">Imposta sui dati TAL</p><strong class="amount money">'+money(d.summary.taxCents)+'</strong><p>Da confermare nel quadro dichiarativo. Non è un importo da versare.</p></div><div><strong>Bozza da completare</strong><p>'+d.counts.complete+' dati compilati · '+d.counts.confirm+' da confermare</p><small>Versione '+record.revision+' · salvata il '+esc(new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(record.createdAt)))+'</small></div></section>'+
  '<div class="breakdown declaration-totals">'+summary.map(([label,n])=>'<div><span>'+label+'</span><strong class="money">'+money(n)+'</strong></div>').join('')+'</div>'+
  '<details class="declaration-detail" data-declaration-detail="missing" open><summary>Cosa resta da verificare</summary>'+
  '<ul>'+[...new Set([...d.issues.map(i=>i.message),'Dati anagrafici e altri redditi della persona.','Perdite, crediti, ritenute e versamenti dichiarativi.','Raccordo previdenziale RR e dati informativi RS.'])].map(m=>'<li>'+esc(m)+'</li>').join('')+'</ul><p class="small">'+missing.length+' campi non completati; il dettaglio distingue dati mancanti e parti non supportate.</p></details>'+
  reviews+analytic+detail+audit+professional+'<p class="small muted declaration-notice">Bozza di lavoro professionale. Non è una dichiarazione pronta all’invio né un file telematico. I dati degli altri redditi e i quadri non coperti devono essere verificati dallo Studio.</p></div>';
}
