import {confirmationLabel} from './workflow-view.js';
import {managementLabel} from './workflow-view.js';
// Presentation only. Every monetary tax value is returned by the trusted service/Worker.
const labels={year:'L’annualità fiscale',activity:'L’attività svolta (codice ATECO)',start:'La data di inizio attività',requirements:'I requisiti per il forfettario',startup:'I dati sull’avvio dell’attività',pension:'La gestione previdenziale','tax-planning':'I dati dei versamenti e degli acconti','paid-contributions':'I contributi già versati','activity-resolution':'La conferma dell’attività svolta',ledger:'L’attribuzione degli incassi all’attività','fiscal-details':'Alcuni dati del profilo fiscale'};
export function fiscalView({r,state,mode,heading,button,link,href,euro,esc,label}){
 const taxes=r.page==='tasse';
 if(state.phase!=='ready')return heading(taxes?'Tasse e contributi':r.role==='studio'?'Riepilogo':'Oggi')+(state.phase==='loading'?'<p role="status" aria-busy="true">Aggiornamento della situazione…</p>':'<p role="alert">'+(state.phase==='forbidden'?'Questa posizione non è più disponibile.':state.error==='conflict'||state.error==='stale'?'I dati sono cambiati durante il calcolo. Aggiorna la situazione.':state.error==='limited'?'Il servizio è occupato. Attendi un momento e riprova.':'Calcolo non disponibile. Le stime precedenti non sono aggiornate e non vengono mostrate.')+'</p>'+button('fiscal-retry','Riprova'));
 const d=state.data,v=d.worker?.result,forecast=mode==='forecast'&&taxes,projection=forecast&&d.forecastAvailable?v?.projected:null;
 const money=n=>Number.isSafeInteger(n)?euro(n):'Da definire';
 const valid=(out,key)=>out?.status!=='blocked'?out?.value?.[key]:null;
 const reserve=d.reserveInputsComplete?(forecast?projection?.reserveCents:v?.reserveCents):null;
 const tax=forecast?projection?.taxCents:valid(v?.tax,'taxCents'),social=forecast?projection?.socialCents:valid(v?.social,'totalCents');
 const income=forecast?projection?.income:v?.income;
 const date=s=>new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(s));
 const events=(v?.calendar?.value?.events||[]).filter(e=>/^\d{4}-\d{2}-\d{2}$/.test(e.date||'')).sort((a,b)=>a.date.localeCompare(b.date));
 const today=new Date().toISOString().slice(0,10),next=events.find(e=>e.date>=today);
 const eventLabel=e=>e.entity==='ERARIO'?(e.kind==='advance_second_or_single'?'Acconto imposta':'Saldo o acconto imposta'):'Contributi previdenziali';
 const calendar=()=>'<section id="payment-detail" class="payment-detail" tabindex="-1"><h2>Prossimo pagamento previsto</h2>'+(next?'<p>'+date(next.date)+' · '+esc(eventLabel(next))+'</p><strong class="amount money">'+money(next.amountCents)+'</strong>':'<p>Nessun prossimo pagamento determinabile dai dati disponibili.</p>')+(next?'<p class="small muted">Non sommare automaticamente questo importo alla riserva. Da verificare prima del versamento.</p>':'')+(v?.calendar?.status==='warning'?'<p class="small">Il calendario è parziale: alcune scadenze richiedono una verifica.</p>':'')+'</section>';
 const missing=d.missing.length?'<section class="task-card"><h2>'+(d.missing.length===1&&d.missing[0]==='paid-contributions'?'Contributi versati da indicare':'Dati da completare')+'</h2>'+(d.missing.some(k=>k!=='paid-contributions')?'<ul>'+d.missing.filter(k=>k!=='paid-contributions').map(k=>'<li>'+esc(labels[k]||'Un dato da verificare')+'</li>').join('')+'</ul><p class="small">Necessari per completare il calcolo.</p>':'')+(d.missing.includes('paid-contributions')?button('pension','Indica i versamenti'):'')+'</section>':'';
 const status=d.worker?.status==='blocked'?'<p role="status">Alcuni risultati non sono calcolabili. Gli importi mancanti restano da definire.</p>':'';
 const meanings='<details class="amount-meaning"><summary>Riserva e pagamento: la differenza</summary><p>La riserva è una stima di imposte e contributi, al netto dei versamenti indicati. Non misura il denaro già messo da parte.</p><p>Il pagamento previsto riguarda una scadenza specifica. Non è un importo da aggiungere automaticamente alla riserva.</p></details>';
 if(!taxes)return heading(r.role==='studio'?'Riepilogo':'Oggi',esc(label),button('fiscal-retry','Aggiorna','','text-link'))+'<div class="today-grid"><section class="income-hero"><div class="income-line"><div><p class="eyebrow">Incassati nel '+d.year+'</p><strong class="hero-amount money">'+money(d.receivedCents)+'</strong></div>'+link(href(r,'entrate'),'Vedi entrate')+'</div><div class="reserve"><div><p class="reserve-label">Riserva fiscale stimata</p><strong class="amount money">'+money(reserve)+'</strong><p>Sulla situazione attuale</p></div>'+link(href(r,'tasse'),'Dettaglio riserva','text-link',false)+'</div>'+meanings+status+'</section>'+missing+'</div>';
 const forecastNote=forecast?d.forecastAvailable?'<p>È un’ipotesi di fine anno, non un importo già dovuto. Si basa sulle entrate previste che hai indicato.</p>':'<p>Previsione non disponibile: mancano le entrate previste a fine anno.</p>':'';
 const obligations=forecast?(projection?.pensionObligations||[]):(v?.pensionObligations||d.obligations||[]);
 const partial=obligations.some(o=>o.state!=='CALCULABLE');
 const obligationRows=obligations.length?'<details class="tax-detail"'+(partial?' open':'')+'><summary>Contributi per gestione</summary><p class="small">Dovuto stimato sugli incassi '+(forecast?'previsti':'registrati')+'. I versamenti effettivi sono indicati separatamente.</p><div class="breakdown">'+obligations.map(o=>'<div><span>'+esc(o.managementId?.startsWith('INPS_')?managementLabel(o.managementId):(o.label||managementLabel(o.managementId)))+'</span><strong class="money">'+(o.state==='CALCULABLE'?money(o.dueCents):'Da verificare')+'</strong></div>').join('')+'</div>'+(partial?'<p role="status">Il totale dei contributi è da definire: una o più gestioni richiedono una verifica.</p>':'')+'</details>':'';
 const rows=[['Acconti imposta già versati',d.advanceFact?.state==='conflict'?null:d.advanceFact?.amountCents??null],['Reddito forfettario',valid(income,'grossIncomeCents')],['Imposta sostitutiva',tax],['Contributi dovuti · stima',social],['Contributi versati registrati',d.paidContributionCents]];
 const payments='<section class="pension-records"><h2>Contributi già versati</h2><p>'+(d.pensionState==='unknown'?'Non hai ancora indicato se hai effettuato versamenti.':d.pensionState==='none'?'Nessun versamento dichiarato per questa annualità.':'Il calcolo considera solo i versamenti registrati.')+'</p>'+button('pension',d.pensionState==='unknown'?'Indica i versamenti':'Aggiungi un versamento')+(d.pensionPayments.length?'<ul class="receipt-list">'+d.pensionPayments.map(p=>'<li><span>'+date(p.paidDate)+'<br><small>'+esc(confirmationLabel(p.confirmation,p.verifications))+'</small></span><strong>'+money(p.amountCents)+'</strong>'+(r.role==='studio'&&!p.verifications?.some(v=>v.state==='studio_verified')&&p.confirmation?.state!=='studio_verified'?button('fact-verify:pension_payment:'+p.id,'Verifica versamento','','text-link'):'')+'</li>').join('')+'</ul>':'')+'</section>';
 return heading('Tasse e contributi','Anno '+d.year,button('fiscal-retry','Aggiorna','','text-link'))+'<div class="segmented" aria-label="Periodo della stima"><button data-tax="current" aria-pressed="'+!forecast+'">Situazione attuale</button><button data-tax="forecast" aria-pressed="'+forecast+'">Previsione di fine anno</button></div>'+missing+status+'<div class="tax-layout"><section><div class="tax-total" id="reserve-detail" tabindex="-1"><p class="eyebrow">Riserva fiscale stimata'+(forecast?' · a fine anno':'')+'</p><strong class="amount money">'+money(reserve)+'</strong>'+forecastNote+'</div>'+meanings+'<div class="breakdown">'+rows.map(([name,n])=>'<div><span>'+name+'</span><strong class="money">'+money(n)+'</strong></div>').join('')+'</div>'+obligationRows+'<details class="tax-detail"><summary>Dettaglio del calcolo</summary><dl><dt>Reddito imponibile</dt><dd>'+money(valid(income,'taxableIncomeCents'))+'</dd><dt>Contributi dedotti dal reddito</dt><dd>'+money(valid(income,'deductibleContributionsCents'))+'</dd><dt>Saldo imposta · situazione attuale</dt><dd>'+money(v?.advances?.value?.balance?.debitCents)+'</dd><dt>Acconti · situazione attuale</dt><dd>'+money(valid(v?.advances,'totalAdvanceCents'))+'</dd></dl>'+(r.role==='studio'?'<p class="small">Versione calcolo: '+esc(d.worker?.engineVersion||'Calcolo non disponibile')+'</p>':'')+'</details>'+payments+'</section><section>'+'<p>'+link(href(r,'pagamenti'),'Pagamenti e acconti versati')+'</p>'+calendar()+'<details class="tax-detail"><summary>Calendario della situazione attuale</summary>'+events.map(e=>'<p>'+date(e.date)+' · '+esc(eventLabel(e))+' · '+money(e.amountCents)+'</p>').join('')+'</details></section></div>';
}
