import test from 'node:test';
import assert from 'node:assert/strict';
import {createFiscalController} from './fiscal-controller.js';
import {createTalDataService} from './tal-data-service.js';
import {fiscalView} from './fiscal-view.js';
const id='00000000-0000-4000-8000-000000000301';
const tick=()=>new Promise(r=>setImmediate(r));
function harness(){let listener,resolve,reject;const auth={subscribe(fn){listener=fn;fn({phase:'ready',user:{id:'a'},selected:{context_type:'personal',context_id:id}});}};
 const c=createFiscalController({auth,service:{calculateFiscal:()=>new Promise((a,b)=>{resolve=a;reject=b;})}});c.select(id,2026);
 return {c,answer:v=>resolve(v),fail:code=>reject({code}),change:v=>listener(v)};
}
test('calculation loading never presents a cached value',async()=>{const h=harness();await tick();assert.equal(h.c.getState().data,null);h.answer({receivedCents:100});await tick();assert.equal(h.c.getState().phase,'ready');const p=h.c.refresh();assert.equal(h.c.getState().data,null);h.answer({receivedCents:200});await p;assert.equal(h.c.getState().data.receivedCents,200);});
for(const code of ['forbidden','expired','conflict','unavailable','limited'])test('calculation '+code+' removes all old amounts',async()=>{const h=harness();await tick();h.answer({receivedCents:100});await tick();const p=h.c.refresh();h.fail(code);await p;assert.equal(h.c.getState().data,null);assert.ok(['forbidden','error'].includes(h.c.getState().phase));});
test('payment invalidation discards an earlier in-flight calculation',async()=>{const h=harness();await tick();const old=h.answer;const resolveOld=h.c.refresh();h.c.invalidate();h.answer({receivedCents:100});await resolveOld;assert.equal(h.c.getState().data,null);const current=h.c.refresh();h.answer({receivedCents:200});await current;assert.equal(h.c.getState().data.receivedCents,200);});
test('logout prevents a late calculation from repopulating the view',async()=>{const h=harness();await tick();h.change({phase:'signed-out'});h.answer({receivedCents:100});await tick();assert.equal(h.c.getState().data,null);});
test('context switch prevents another position result appearing',async()=>{const h=harness();await tick();h.change({phase:'ready',user:{id:'a'},selected:{context_type:'studio',context_id:'other'}});h.answer({receivedCents:100});await tick();assert.equal(h.c.getState().data,null);});
const auth={getState:()=>({user:{id:'a'}}),withContextSession:fn=>fn({config:{supabaseUrl:'https://example.test',publishableKey:'public-test'},token:'synthetic',context:{context_type:'personal',context_id:id}})};
test('browser submits only workspace/year, never fiscal facts to Worker',async()=>{let seen;const service=createTalDataService({auth,fetchImpl:async(url,opts)=>{seen={url,opts};return Response.json({workspaceId:id,year:2026,dataRevision:1,missing:[],pensionPayments:[]});}});await service.calculateFiscal(id,2026);assert.deepEqual(JSON.parse(seen.opts.body),{workspaceId:id,year:2026});assert.ok(seen.url.endsWith('/functions/v1/tal-calculate-fiscal'));assert.equal(seen.opts.cache,'no-store');assert.equal(seen.opts.redirect,'error');});
test('foreign or malformed calculation result rejected',async()=>{const service=createTalDataService({auth,fetchImpl:async()=>Response.json({workspaceId:'other',year:2026,dataRevision:1,missing:[],pensionPayments:[]})});await assert.rejects(service.calculateFiscal(id,2026),{code:'unavailable'});});
const helpers={heading:t=>t,button:(a,t)=>t,link:()=>'',href:()=>'',euro:n=>'CENTS '+n,esc:s=>String(s),label:'Synthetic'};

test('multiple obligations show due separately, partial total is never manufactured',()=>{const text=fiscalView({...helpers,r:{page:'tasse'},mode:'current',state:{phase:'ready',data:{year:2026,missing:[],pensionState:'provided',pensionPayments:[],paidContributionCents:12345,obligations:[{managementId:'GS',label:'Gestione Separata',state:'CALCULABLE',dueCents:600000},{managementId:'CASSA',label:'Cassa da verificare',state:'PARTIAL',dueCents:null}],worker:{status:'blocked',result:{social:{status:'blocked',value:{totalCents:null,knownSubtotalCents:600000}}}}}}});assert.match(text,/Contributi per gestione/);assert.match(text,/Gestione Separata/);assert.match(text,/CENTS 600000/);assert.match(text,/Da verificare/);assert.match(text,/totale dei contributi è da definire/);assert.match(text,/CENTS 12345/);});
test('forecast never substitutes current per-obligation amounts',()=>{const text=fiscalView({...helpers,r:{page:'tasse'},mode:'forecast',state:{phase:'ready',data:{year:2026,missing:[],pensionState:'none',pensionPayments:[],paidContributionCents:0,forecastAvailable:false,obligations:[{managementId:'GS',state:'CALCULABLE',dueCents:912345}],worker:{result:{}}}}});assert.doesNotMatch(text,/912345/);});
test('unknown contribution and reserve render missing, not zero',()=>{const text=fiscalView({...helpers,r:{page:'tasse'},mode:'current',state:{phase:'ready',data:{year:2026,missing:['paid-contributions'],pensionState:'unknown',pensionPayments:[],paidContributionCents:null,receivedCents:100}}});assert.match(text,/Contributi versati da indicare/);assert.match(text,/Da definire/);assert.doesNotMatch(text,/CENTS 0/);});
test('forecast cannot fall back to actual amounts when absent',()=>{const text=fiscalView({...helpers,r:{page:'tasse'},mode:'forecast',state:{phase:'ready',data:{year:2026,missing:[],pensionState:'none',pensionPayments:[],paidContributionCents:0,forecastAvailable:false,worker:{result:{reserveCents:123456}}}}});assert.match(text,/Previsione non disponibile/);assert.doesNotMatch(text,/123456/);});
test('pension declaration and payment retry deduplicate concurrent submission',async()=>{let count=0;const service=createTalDataService({auth,fetchImpl:async(url,opts)=>{count++;assert.ok(url.endsWith('tal_record_pension_payment'));const b=JSON.parse(opts.body);assert.equal(b.p_payload.action,'none');await tick();return Response.json({year:2026,state:'none',paymentId:null,dataRevision:2});}});const p={year:2026,action:'none',expectedDataRevision:1},key='00000000-0000-4000-8000-000000000401';assert.deepEqual(...await Promise.all([service.recordPension(id,p,key),service.recordPension(id,p,key)]));assert.equal(count,1);});
