import test from 'node:test';import assert from 'node:assert/strict';
import {createAuthContextService} from './auth-context-service.js';
import {createOnboardingService,inviteCode,parseInvite,newInviteToken,activityCanBeSaved} from './onboarding-service.js';
const uid='11000000-0000-4000-8000-000000000001',wid='11000000-0000-4000-8000-000000000002';
const config={supabaseUrl:'https://'+'a'.repeat(20)+'.supabase.co',publishableKey:'sb_publishable_'+'x'.repeat(25)};
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
function authHarness({signup=Response.json({id:uid}),contexts=[]}={}){
 const storage=memory(),preferenceStorage=memory(),calls=[];
 const fetchImpl=async(url,options)=>{calls.push({url,options});if(url.endsWith('/signup'))return signup;
  if(url.includes('/token'))return Response.json({access_token:'synthetic.token.only',refresh_token:'test-only',expires_in:3600,user:{id:uid}});
  if(url.endsWith('/user'))return Response.json({id:uid,email:'synthetic@tal-s11.test'});
  if(url.includes('tal_list_my_contexts'))return Response.json(contexts);
  if(url.includes('/logout'))return new Response(null,{status:204});throw Error('unexpected');};
 return {auth:createAuthContextService({config,fetchImpl,storage,preferenceStorage,lock:(_k,f)=>f()}),calls,storage};
}
test('public signup requires confirmation and never provisions or stores a session',async()=>{const h=authHarness();await h.auth.signup('synthetic@tal-s11.test','synthetic-password');assert.equal(h.auth.getState().phase,'check-email');assert.equal(h.storage.getItem(h.auth.sessionKey),null);assert.equal(h.calls.length,1);assert.deepEqual(JSON.parse(h.calls[0].options.body),{email:'synthetic@tal-s11.test',password:'synthetic-password'});assert.ok(!JSON.stringify(h.auth.getState()).includes('password'));});
test('unexpected autoconfirm session cannot bypass product confirmation',async()=>{const h=authHarness({signup:Response.json({access_token:'synthetic.token.only'})});await h.auth.signup('synthetic@tal-s11.test','synthetic-password');assert.equal(h.auth.getState().phase,'error');assert.equal(h.storage.getItem(h.auth.sessionKey),null);});
test('signup errors do not enumerate existing accounts',async()=>{for(const code of ['email_exists','email_address_invalid']){const h=authHarness({signup:Response.json({error_code:code},{status:400})});await h.auth.signup('synthetic@tal-s11.test','synthetic-password');assert.equal(h.auth.getState().phase,'signed-out');assert.doesNotMatch(h.auth.getState().message,/exists|invalid/);}});
test('identity port works before a selected context and never exposes token in state',async()=>{const h=authHarness();await h.auth.login('synthetic@tal-s11.test','test');assert.equal(h.auth.getState().phase,'empty');assert.equal(await h.auth.withIdentitySession(s=>!!s.token),true);assert.doesNotMatch(JSON.stringify(h.auth.getState()),/synthetic.token/);});
test('late bootstrap cannot restore anything after logout',async()=>{const h=authHarness();await h.auth.login('synthetic@tal-s11.test','test');let release;const task=h.auth.withIdentitySession(()=>new Promise(r=>release=r));await new Promise(r=>setTimeout(r,0));await h.auth.logout();release({personal:{id:wid}});await assert.rejects(task,{code:'stale'});});
test('identity port rejects signed out and expired sessions clear identity',async()=>{const h=authHarness();await h.auth.restore();await assert.rejects(h.auth.withIdentitySession(()=>{}),{code:'forbidden'});await h.auth.login('synthetic@tal-s11.test','test');await assert.rejects(h.auth.withIdentitySession(()=>{throw Object.assign(Error(),{code:'expired'});}),{code:'expired'});assert.equal(h.auth.getState().phase,'signed-out');});
function harness(){
 const calls=[],ctx={context_type:'personal',context_id:wid};
 const h={ctx,response:{status:'pending',linkId:uid,revision:1},fail:false,pause:null};
 const auth={getState:()=>({user:{id:uid},selected:h.ctx}),withIdentitySession:f=>f({config,token:'synthetic.token.only'}),withContextSession:f=>f({config,token:'synthetic.token.only',context:h.ctx})};
 h.service=createOnboardingService({auth,fetchImpl:async(url,o)=>{calls.push({url,o});if(h.pause)await h.pause;if(h.fail)throw Error('lost');return Response.json(h.response);}});h.calls=calls;return h;
}
test('invitation token is random 256-bit and parser rejects TAL IDs and malformed values',()=>{const a=newInviteToken(),b=newInviteToken();assert.match(a,/^[0-9a-f]{64}$/);assert.notEqual(a,b);assert.deepEqual(parseInvite(inviteCode(uid,a)),{p_link_id:uid,p_token:a});for(const value of ['TAL-ABCDEFGH',uid,'TALI1.'+uid+'.'+a+'.extra'])assert.throws(()=>parseInvite(value),{code:'invalid'});});
test('provisioning has no caller identity or scope input',async()=>{const h=harness();await h.service.provisionPersonal();const body=JSON.parse(h.calls[0].o.body);assert.deepEqual(body,{});assert.ok(!h.calls[0].o.headers['x-tal-context']);});
test('double submit coalesces exact pending invite, successful retry still reaches server',async()=>{const h=harness();let release;h.pause=new Promise(r=>release=r);const args={p_recipient_email:'synthetic@tal-s11.test',p_token:newInviteToken(),p_idempotency_key:'same'};const a=h.service.createInvite(args),b=h.service.createInvite(args);assert.equal(h.calls.length,1);release();await Promise.all([a,b]);h.pause=null;await h.service.createInvite(args);assert.equal(h.calls.length,2);assert.equal(h.calls[0].o.body,h.calls[1].o.body);});
test('lost response retry retains exact key, token, revision and scope',async()=>{const h=harness(),args={p_recipient_email:'synthetic@tal-s11.test',p_token:newInviteToken(),p_idempotency_key:'same'};h.fail=true;await assert.rejects(h.service.createInvite(args),{code:'uncertain'});h.fail=false;await h.service.createInvite(args);assert.equal(h.calls[0].o.body,h.calls[1].o.body);});
test('context supplied by client input cannot override selected context',async()=>{const h=harness();await h.service.saveOnboarding({p_context:'studio:'+uid});assert.equal(JSON.parse(h.calls[0].o.body).p_context,'personal:'+wid);});
test('accept wrong context fails before any request',()=>{const h=harness();assert.throws(()=>h.service.acceptInvite(inviteCode(uid,newInviteToken()),{context:'studio:'+uid,revision:1},'key'),{code:'context'});assert.equal(h.calls.length,0);});
test('accept and revoke use frozen RPCs, no direct writes',async()=>{const h=harness();await h.service.acceptInvite(inviteCode(uid,newInviteToken()),{context:'personal:'+wid,revision:2},'key');await h.service.revokeLink({id:uid,revision:3},'next');assert.deepEqual(h.calls.map(c=>new URL(c.url).pathname),['/rest/v1/rpc/tal_accept_link','/rest/v1/rpc/tal_revoke_link']);assert.equal(JSON.parse(h.calls[1].o.body).p_expected_revision,3);});
test('all bootstrap requests omit cookies, disable caches and keep credentials out of URL',async()=>{const h=harness();await h.service.getOnboarding();await h.service.provisionStudio('Synthetic Studio');await h.service.listLinks();for(const c of h.calls){assert.equal(c.o.credentials,'omit');assert.equal(c.o.cache,'no-store');assert.equal(c.o.redirect,'error');assert.ok(!new URL(c.url).search);assert.doesNotMatch(c.url,/token|password|email/);}});
test('ATECO missing fiscal mapping stays unresolved; unknown code rejected',()=>{assert.equal(activityCanBeSaved({status:'calculated'}),true);assert.equal(activityCanBeSaved({status:'blocked',diagnostics:[{code:'ATECO_AMBIGUOUS_COEFFICIENT'}]}),true);assert.equal(activityCanBeSaved({status:'blocked',diagnostics:[{code:'ATECO_CODE_NOT_FOUND'}]}),false);assert.equal(activityCanBeSaved({status:'blocked',diagnostics:[]}),false);});
test('resolver transports only year/code and preserves authoritative output',async()=>{const h=harness();h.response={status:'warning',engineVersion:'test',result:{}};assert.deepEqual(await h.service.resolveActivity(2026,'62.10.00'),h.response);assert.deepEqual(JSON.parse(h.calls[0].o.body),{year:2026,code:'62.10.00'});assert.ok(h.calls[0].url.endsWith('/functions/v1/tal-resolve-activity'));});

