const names={DRAFT:'Da controllare',READY:'Predisposto',DOWNLOADED:'Scaricato · pagamento non registrato',PAID:'Pagamento documentato',STALE:'Da aggiornare',BLOCKED:'Da verificare'};
export function paymentsView({state,heading,button,esc,euro,studio,base}){
 const header=heading('Pagamenti','Redditi 2025 · versamenti 2026');
 if(state.phase!=='ready')return header+'<p role="'+(state.phase==='loading'?'status':'alert')+'">'+(state.phase==='loading'?'Verifica di dichiarazione e versamenti…':state.phase==='forbidden'?'Questa posizione non è più disponibile.':'Non possiamo mostrare pagamenti aggiornati. Riprova.')+'</p>'+(state.phase==='loading'?'':button('payments-retry','Riprova'));
 const d=state.data.draft,money=n=>Number.isSafeInteger(n)?euro(n):'Da verificare';
 const reconciled=Object.hasOwn(d.settlement,'remainingBalanceCents');
 const groups=[...d.groups].sort((a,b)=>(a.status==='PAID')-(b.status==='PAID')||a.key.localeCompare(b.key));
 const cards=groups.map((g,i)=>'<article class="payment-row"><div><p class="eyebrow">'+esc(names[g.status])+'</p><h2>'+esc(g.dueDate?new Intl.DateTimeFormat('it-IT',{dateStyle:'long'}).format(new Date(g.dueDate+'T12:00:00')):'Scadenza da verificare')+'</h2><p>'+g.lines.map(l=>esc((l.obligationType==='balance'?'Saldo ':'Acconto ')+(l.section==='INPS'?'contributi INPS ':'imposta ')+l.referenceTaxYear)).join(' + ')+'</p></div><div class="payment-row-action"><strong class="amount money">'+money(g.totalCents)+'</strong>'+button('payments-open:'+encodeURIComponent(g.key),g.status==='PAID'?'Apri F24':'Controlla F24')+'</div></article>').join('');
 const diagnostics=[...new Set(d.diagnostics.map(x=>x.message))];
 const blocked=d.blocked.map(p=>'<li><strong>'+esc(p.managementId.replaceAll('_',' '))+'</strong> — '+esc(p.message)+'</li>').join('');
 return header+'<div class="payments-page"><p class="small">'+(studio?'Il cliente vede gli stessi modelli predisposti qui.':'I modelli predisposti dallo Studio sono disponibili qui.')+' Scaricare un F24 non significa pagarlo.</p>'+
 (cards||'<div class="empty-state"><h2>'+(d.settlement.completeness==='COMPLETE'?'Nessun saldo fiscale da versare':'Pagamenti da verificare')+'</h2><p>'+(d.settlement.completeness==='COMPLETE'?'Gli eventuali acconti e contributi restano distinti dal saldo.':'Servono le verifiche dello Studio prima di predisporre gli F24.')+'</p></div>')+
 (diagnostics.length||blocked?'<section class="payment-checks">'+(cards?'<h2>Da verificare</h2>':'')+'<ul>'+diagnostics.map(m=>'<li>'+esc(m)+'</li>').join('')+blocked+'</ul></section>':'')+
 (studio?button('payments-review','Verifica versamenti e crediti','','button secondary'):'')+
 '<details class="declaration-detail"><summary>Come si arriva agli importi</summary><div class="breakdown"><div><span>Imposta del 2025</span><strong>'+money(d.settlement.grossLiabilityCents)+'</strong></div><div><span>Acconti 2025 verificati</span><strong>'+money(d.settlement.priorPaymentsCents)+'</strong></div>'+(reconciled?'<div><span>Saldo già versato e documentato</span><strong>'+money(d.settlement.documentedPaidCents)+'</strong></div>':'')+'<div><span>Saldo ancora da versare</span><strong>'+money(reconciled?d.settlement.remainingBalanceCents:d.settlement.balanceDueCents)+'</strong></div><div><span>Credito risultante · non utilizzato</span><strong>'+money(d.credit.availableCents)+'</strong></div></div><p class="small">Bozza dichiarativa · versione '+esc(d.declarationRevision)+'. Termine ordinario, pagamento non rateizzato. Compensazioni, differimenti e contributi non verificati non vengono applicati.</p>'+
 '<a class="text-link" href="'+esc(base+'dichiarazione')+'">Apri la bozza dichiarativa</a> · <a class="text-link" href="'+esc(base+'tasse')+'">Situazione fiscale</a></details>'+
 '<p class="small muted">Modelli di lavoro da controllare prima del versamento. Nessun invio telematico o pagamento bancario viene eseguito da TAL. Per termini già trascorsi occorre verificare il ravvedimento, qui non calcolato.</p></div>';
}
